import { getFileFromPath, convSecToStr, convStrToSec, COLOR } from "./util";
import { getClipBlocks, hasClipBlockExtensions, validateClipBlocks } from "./subtitle_blocks";

const AUDIO_EXTENSIONS = [".mp3", ".wav", ".m4a", ".aac", ".flac", ".ogg"];
const IMAGE_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"];
const AUTO_GENERATED_VC_JSON = Symbol("autoGeneratedVcJson");
// 編集トラックの id は scriptFiles 配列インデックスと一致させる不変条件を持つ
// （トラックは末尾追加のみで並べ替え・削除されない）。画像トラックはこの id 空間と
// 衝突しないよう専用の高い基底値を使う。store/Style_Ribbon の scriptFiles[id] 参照は
// この不変条件に依存している。
const IMAGE_TRACK_ID_BASE = 1_000_000;

function hasExtension(name, extensions) {
    const lower = name.toLowerCase();
    return extensions.some((ext) => lower.endsWith(ext));
}

function markAutoGenerated(data, vcJsonName) {
    Object.defineProperty(data, AUTO_GENERATED_VC_JSON, {
        value: vcJsonName,
        enumerable: false,
    });
    return data;
}

export function getAutoGeneratedVcJsonName(data) {
    return data?.[AUTO_GENERATED_VC_JSON] ?? null;
}

// スタイルの色をすべて正準形 #rrggbbaa に統一する（カラーピッカーが rgba() 文字列を
// 受け取って NaN 化する不具合を根本から断つ）。色を持つ全プロジェクトデータ生成口で適用する。
function normalizeStyleColors(styles) {
    if (!styles) return styles;
    for (const key of Object.keys(styles)) {
        const style = styles[key];
        if (!style) continue;
        if (typeof style.textColor === "string") style.textColor = COLOR.toHex8(style.textColor);
        for (const sub of ["outline1", "outline2", "shadow"]) {
            if (style[sub] && typeof style[sub].color === "string") {
                style[sub].color = COLOR.toHex8(style[sub].color);
            }
        }
    }
    return styles;
}

function getSortedFileEntries(entries) {
    return entries
        .filter((entry) => entry.kind === "file")
        .sort((a, b) => a.name.localeCompare(b.name, "ja"));
}

function getBaseName(filename) {
    return filename.replace(/\.[^/.]+$/, "");
}

function getGeneratedVcJsonName(baseName) {
    return `${baseName || "sample"}.vc_json`;
}

function getDefaultGeneratedTrackName(baseName) {
    return `srt/${baseName || "sample"}.srt`;
}


/*
*　　-- media処理関連 --
*　　vc_jsonファイル単位のメディアデータ（audio、img、srtなど）関連の処理
*/
export function getDefaultMedia(){
    return {
        name: "メディアなし",
        image_data: { currentId: 0, currentImage: null, currentImagePath: null, size: { x: 0, y: 0 } },
        srt_data: [],
        isAudio: true,
        isPlaying: false,
        duration: 0,
        playbackRate: 1,
        volume: 0.5,
      }
}

function cloneSrtData(data) {
    return (data ?? []).map((item) => ({ ...item, ...copyClipBlockExtensions(item), ref: item.ref ?? {} }));
}

function copyClipBlockExtensions(clip) {
    validateClipBlocks(clip);
    const extension = {};
    if (Object.prototype.hasOwnProperty.call(clip, "layout")) extension.layout = { ...clip.layout };
    if (Object.prototype.hasOwnProperty.call(clip, "additionalBlocks")) {
        extension.additionalBlocks = clip.additionalBlocks.map((block) => ({
            ...block,
            ...(block.sentences ? { sentences: [...block.sentences] } : {}),
            ...(block.layout ? { layout: { ...block.layout } } : {}),
        }));
    }
    return extension;
}

function normalizeInlineNewlines(text) {
    return String(text ?? "").replace(/\r(?!\n)/g, "\n");
}

function splitTextToSentences(text) {
    const lines = normalizeInlineNewlines(text).replace(/\r\n/g, "\n").split("\n");
    const sentences = [];
    let current = [];

    for (const line of lines) {
        if (isParagraphSeparatorLine(line)) {
            if (current.length) {
                sentences.push(current.join("\n"));
                current = [];
            }
            continue;
        }
        current.push(line);
    }
    if (current.length) sentences.push(current.join("\n"));

    return sentences
        .map((sentence) => sentence.trim())
        .filter((sentence) => sentence.length > 0);
}

function joinSentencesWithParagraphBreak(sentences) {
    return (sentences ?? []).map((sentence) => normalizeInlineNewlines(sentence)).join("\r\n");
}

function isParagraphSeparatorLine(line) {
    return String(line ?? "").trim() === "" || /^[　]+$/.test(String(line ?? ""));
}

function isSrtParagraphSeparatorLine(line) {
    return isParagraphSeparatorLine(line);
}

function parseSrtBodyText(body) {
    const lines = String(body ?? "").replace(/\r\n|\r|\n/g, "\n").replace(/\n+$/g, "").split("\n");
    const sentences = [];
    let current = [];

    for (const line of lines) {
        if (isSrtParagraphSeparatorLine(line)) {
            if (current.length) {
                sentences.push(current.join("\n"));
                current = [];
            }
            continue;
        }
        current.push(line);
    }
    if (current.length) sentences.push(current.join("\n"));

    const text = sentences.length ? joinSentencesWithParagraphBreak(sentences) : "";
    return { text, sentences };
}

function serializeSrtBodyText(item) {
    const sentences = Array.isArray(item?.sentences) && item.sentences.length
        ? item.sentences
        : splitTextToSentences(getSrtItemText(item));
    return sentences
        .map((sentence) => normalizeInlineNewlines(sentence).replace(/\r\n/g, "\n").replace(/\n/g, "\r\n"))
        .join("\r\n　\r\n");
}

export function getSrtItemText(item) {
    if (!item) return "";
    if (Array.isArray(item.sentences)) {
        return joinSentencesWithParagraphBreak(item.sentences);
    }
    return normalizeInlineNewlines(item.text ?? "");
}

export function setSrtItemText(item, text) {
    if (!item) return;
    const normalized = normalizeInlineNewlines(text);
    const sentences = splitTextToSentences(normalized);
    if (sentences.length > 1) {
        item.sentences = sentences;
        item.text = joinSentencesWithParagraphBreak(sentences);
    } else {
        delete item.sentences;
        item.text = sentences[0] ?? normalized;
    }
}

export function setSrtItemSentence(item, index, text) {
    if (!item || !Array.isArray(item.sentences)) return;
    item.sentences[index] = normalizeInlineNewlines(text);
    item.text = joinSentencesWithParagraphBreak(item.sentences);
}

function getDurationFromSrtData(tracks) {
    return Math.max(0, ...tracks.flatMap((track) => (track.data ?? []).map((item) => item.endTime || 0)));
}

function serializeJsonSrtItem(item) {
    const sentences = Array.isArray(item?.sentences) && item.sentences.length
        ? item.sentences.map((sentence) => normalizeInlineNewlines(sentence).trim()).filter(Boolean)
        : splitTextToSentences(item?.text ?? "");
    const text = sentences.length > 1 ? joinSentencesWithParagraphBreak(sentences) : normalizeInlineNewlines(item?.text ?? sentences[0] ?? "");
    return {
        ...item,
        ...copyClipBlockExtensions(item),
        text,
        ...(sentences.length > 1 ? { sentences } : {}),
    };
}

export function syncJsonDataFromMedia(jsonData, media) {
    if (!jsonData?.scriptFiles || !media?.srt_data) return jsonData;
    const editableTracks = media.srt_data.filter((track) => !track.isImageTrack);
    return {
        ...jsonData,
        scriptFiles: jsonData.scriptFiles.map((scriptFile, index) => {
            const track = editableTracks.find((item) => item.id === index) ?? editableTracks[index];
            if (!track?.data) return scriptFile;
            const { inlineData, ...scriptFileWithoutText } = scriptFile;
            if (scriptFile.filePath) return scriptFileWithoutText;
            return {
                ...scriptFileWithoutText,
                inlineData: track.data.map(serializeJsonSrtItem),
            };
        }),
    };
}

function stripInlineDataFromVcJson(jsondata) {
    if (!jsondata?.scriptFiles) return jsondata;
    const { srtFiles, jsonFiles, ...restJsonData } = jsondata;
    return {
        ...restJsonData,
        scriptFiles: jsondata.scriptFiles.map((scriptFile) => {
            const { inlineData, ...rest } = scriptFile;
            return rest;
        }),
    };
}

async function tryGetFileFromPath(dirHandle, path) {
    try {
        return await getFileFromPath(dirHandle, path);
    } catch (err) {
        console.warn("ファイル読み込みスキップ:", path, err);
        return null;
    }
}

function makeTrack({ id, name, filePath = "", data = [], isImageTrack = false, defaultStyle = "default-style-1", loadStatus = "loaded", loadError = null }) {
    const normalizedData = normalizeSrtItems(cloneSrtData(data));
    return {
        id,
        name,
        file_path: filePath,
        height: 40,
        default_class: defaultStyle,
        isImageTrack,
        loadStatus,
        loadError,
        data: normalizedData,
    };
}

async function loadTrackData(dirHandle, filePath, inlineData) {
    const hasInlineData = Array.isArray(inlineData);
    if (hasInlineData && !filePath) {
        return { data: cloneSrtData(inlineData), loadStatus: "loaded", loadError: null };
    }
    if (!filePath) {
        return { data: [], loadStatus: "unloaded", loadError: "No subtitle file path" };
    }
    try {
        const file = await getFileFromPath(dirHandle, filePath);
        if (!file) throw new Error("Subtitle file not found");
        const text = await file.text();
        const data = filePath.toLowerCase().endsWith(".json")
            ? parseSentenceJsonSubtitle(text)
            : parseSrt(text);
        return { data, loadStatus: "loaded", loadError: null, name: file.name };
    } catch (err) {
        if (hasInlineData && err.name === "NotFoundError") {
            return { data: cloneSrtData(inlineData), loadStatus: "loaded", loadError: null };
        }
        // Parser messages can include file contents; expose only the error category.
        return { data: [], loadStatus: "error", loadError: `Subtitle read/parse failed (${err.name || "Error"})` };
    }
}

export async function getMedia(data,dirHandle) {
    if (!dirHandle || !data || data.name === "dummy") {
      return getDefaultMedia();
    }
    let audio = null;
    let audioUrl = null;
    let imageURL = null;
    let duration = 0;
    try {
    const audiofile = await tryGetFileFromPath(dirHandle, data.audioFilePath);
    if (audiofile) {
      audioUrl = URL.createObjectURL(audiofile);
      audio = new Audio(audioUrl);
      await new Promise((resolve) => {
        audio.onloadedmetadata = resolve;
        audio.onerror = resolve;
      });
      duration = Number.isFinite(audio.duration) ? audio.duration : 0;
      const initialSeek = data.seekTime ?? 0;
      audio.currentTime = duration ? Math.min(initialSeek, duration) : initialSeek;
    }

    const srtDatafiles = [];
    for (const [i, script] of (data.scriptFiles ?? []).entries()) {
      const loaded = await loadTrackData(dirHandle, script.filePath, script.inlineData);
      extendLastClipToDuration(loaded.data, duration);
      srtDatafiles.push(makeTrack({
        ...loaded,
        id: i,
        name: loaded.name || script.name || script.filePath || `${data.name}-${i + 1}.srt`,
        filePath: script.filePath,
        defaultStyle: script.defaultStyle ?? script.default_class ?? "default-style-1",
      }));
    }

    if (!duration) duration = getDurationFromSrtData(srtDatafiles);

    let imagePath = null;
    if (data.imageSrtPath) {
      const loaded = await loadTrackData(dirHandle, data.imageSrtPath);
      extendLastClipToDuration(loaded.data, duration);
      srtDatafiles.push(makeTrack({
        ...loaded,
        id: IMAGE_TRACK_ID_BASE,
        name: loaded.name || data.imageSrtPath,
        filePath: data.imageSrtPath,
        isImageTrack: true,
      }));
      imagePath = loaded.data[0]?.text?.replace(/\\/g, "/") ?? null;
    }
    if (!imagePath && data.imageFilePath) {
      imagePath = data.imageFilePath.replace(/\\/g, "/");
    }
    if (imagePath) {
      const imageFile = await tryGetFileFromPath(dirHandle, imagePath);
      if (imageFile) imageURL = URL.createObjectURL(imageFile);
    }

    return {
      name: data.name,
      audio,
      audioUrl,
      image_data: {
        currentId: 0,
        currentImage: imageURL,
        currentImagePath: imagePath,
        size: { x: 0, y: 0 },
      },
      srt_data: srtDatafiles,
      isAudio: !!audio,
      isPlaying: false,
      duration,
      playbackRate: 1,   // 呼び出し元で現在値に上書きされる
      volume: 0.5,       // 同上
    };
    } catch (err) {
      try {
        audio?.pause();
        if (audio) {
          audio.removeAttribute("src");
          audio.load();
        }
      } catch { /* Still revoke URLs and preserve the original load failure. */ }
      if (audioUrl) URL.revokeObjectURL(audioUrl);
      if (imageURL) URL.revokeObjectURL(imageURL);
      throw err;
    }
  }


/*
*　　-- media処理関連 --
*　　vc_jsonファイル単位のメディアデータ（audio、img、srtなど）関連の処理
*/
export function getDefaultJsonData() {
    const data = {
        name: "dummy",
        seekTime: 0,
        audioFilePath: '',
        imageSrtPath: '',
        scriptFiles: [
            {
                filePath: '',
                defaultStyle: 'dummy',
                x: 100,
                y: 100,
                maxWidth: 500,
                maxHeight: 500,
                boxAlignX: 0,
                boxAlignY: 0,
                textRotate: "horizontal-tb",
                textAlign: "left"
            }
        ],
        styles: {
            dummy: {
                font: "りいポップ角",
                fontSize: 30,
                textColor: "rgba(0, 0, 0,1)",
                letterSpace: 0,
                lineSpace: 10,
                fontStyle: "italic",
                fontWeight: "bold",
                isItalic: false,
                outline1: {
                    enable: true,
                    size: 7,
                    color: "rgba(177, 34, 34, 0.95)"
                },
                outline2: {
                    enable: true,
                    offsetX: 0,
                    offsetY: 0,
                    size: 5,
                    color: "rgba(32, 32, 32, 0.8)"
                },
                shadow: {
                    enable: true,
                    steps: 8,
                    offsetX: 0,
                    offsetY: 0,
                    size: 10,
                    color: "rgba(170, 0, 119, 0.1)",
                    blur: 16
                }
            }
        }
    };
    normalizeStyleColors(data.styles);
    return data;
}
export function getVCJsonData(text, filename = "sample.vc_json") {
    const raw = JSON.parse(text);
    const def = getDefaultJsonData();
    const rawStyles = Object.entries(raw.styles || {});
    const rawScriptFiles = raw.scriptFiles || raw.srtFiles || raw.jsonFiles || [];
    for (const script of rawScriptFiles) {
        if (Array.isArray(script.inlineData)) script.inlineData.forEach(validateClipBlocks);
    }
    const { srtFiles, jsonFiles, ...rawWithoutLegacyScriptFiles } = raw;

    const result = {
        ...def,
        ...rawWithoutLegacyScriptFiles,
        name: raw.name || filename,
        scriptFiles: rawScriptFiles.map((script, i) => ({
            ...def.scriptFiles[0],
            ...script
        })),
        styles: rawStyles.length
            ? Object.fromEntries(rawStyles.map(([key, style]) => {
                const styleData = style ?? {};
                return [key, {
                    ...def.styles.dummy,
                    ...styleData,
                    outline1: { ...def.styles.dummy.outline1, ...styleData.outline1 },
                    outline2: { ...def.styles.dummy.outline2, ...styleData.outline2 },
                    shadow:   { ...def.styles.dummy.shadow,   ...styleData.shadow   }
                }];
            }))
            : def.styles
    };

    normalizeStyleColors(result.styles);
    return ensureProjectHasEditableTrack(result);
}



export function getVoiceJsonData(filename, text) {
    const raw = JSON.parse(text);
    const result = getDefaultJsonData();

    result.name = filename;
    result.seekTime = raw.seekTime || 0;
    result.audioFilePath = raw.audioFile || '';
    result.imageSrtPath = raw.imageSRT || '';
    result.scriptFiles = [];
    // @ts-ignore
    result.styles = {};

    // 各SRTファイルを処理
    raw.srtFiles?.forEach((srt, index) => {
        const styleKey = `default-style-${index + 1}`;

        // スタイル部分を切り出し
        const {
            max_width, max_height, isVertical,
            textAlignSelect, verticalAlignSelect,
            font, fontSize, textColor,
            letter_space, line_space,
            isBold, isItalic,
            outline1, outline2, shadow,
            ...layoutProps
        } = srt;

        const fixColorObject = (obj) => {
            const { color, opacity, ...rest } = obj;
            return {
                ...rest,
                color: COLOR.mergeColorAndOpacity({ color, opacity:1-opacity })
            };
        };
        
        const outline1Fixed = fixColorObject(outline1);
        const outline2Fixed = fixColorObject({ ...outline2 });
        const shadowFixed = fixColorObject({
            ...shadow,
            steps: 1,
            offsetX: 0,
            offsetY: 0
        });

        const align = textAlignSelect == 1 ? "left" : textAlignSelect == 2 ? "center" : "right";
        // scriptFilesに1つ追加（配列形式）
        result.scriptFiles.push({
            ...layoutProps,
            maxWidth: max_width,
            maxHeight: max_height,
            defaultStyle: styleKey,
            textAlign: align,
            textRotate: isVertical ? "vertical-rl" : "horizontal-tb",

        });

        const fontStyle = isItalic ? "italic" : "normal";
        const fontWeight = isBold ? "bold" : "normal";

        // stylesにスタイル登録
        result.styles[styleKey] = {
            font, fontSize, textColor,
            letterSpace: letter_space,
            lineSpace: line_space,
            fontWeight, fontStyle,
            outline1:outline1Fixed, 
            outline2:outline2Fixed, 
            shadow:shadowFixed
        };
    });

    normalizeStyleColors(result.styles);
    return ensureProjectHasEditableTrack(result);
}

function joinSentences(sentences) {
    return (sentences ?? [])
        .map((sentence) => String(sentence ?? "").trim())
        .filter((sentence) => sentence.length > 0)
        .join("\r\n");
}

function parseSentenceJsonSubtitle(text, allowUnrelatedJson = false) {
    const raw = JSON.parse(text);
    const rows = Array.isArray(raw) ? raw : raw?.items;
    if (!Array.isArray(rows)) {
        if (allowUnrelatedJson) return null;
        throw new Error("Invalid subtitle JSON structure");
    }
    if (rows.some((row) => !row || (Object.prototype.hasOwnProperty.call(row, "sentences")
        ? !Array.isArray(row.sentences) || row.sentences.some((sentence) => typeof sentence !== "string")
        : typeof row.text !== "string"))) {
        throw new Error("Invalid subtitle sentences");
    }
    return rows.map((row) => ({
        startTimeStr: row.start,
        endTimeStr: row.end,
        startTime: convStrToSec(row.start),
        endTime: convStrToSec(row.end),
        ...(Array.isArray(row.sentences) ? {
            sentences: row.sentences.map((sentence) => normalizeInlineNewlines(sentence).trim()).filter((sentence) => sentence.length > 0),
            text: joinSentences(row.sentences),
        } : { text: normalizeInlineNewlines(row.text) }),
        ...copyClipBlockExtensions(row),
        ref: {},
    }));
}

function getDefaultStyleData() {
    const def = getDefaultJsonData();
    return {
        ...def.styles.dummy,
        fontSize: 42,
        textColor: "rgba(255, 255, 255,1)",
        fontStyle: "normal",
        fontWeight: "bold",
        lineSpace: 10,
        outline1: {
            ...def.styles.dummy.outline1,
            size: 5,
            color: "rgba(0, 0, 0, 0.95)",
        },
        outline2: {
            ...def.styles.dummy.outline2,
            enable: false,
        },
        shadow: {
            ...def.styles.dummy.shadow,
            enable: true,
            size: 2,
            blur: 6,
            color: "rgba(0, 0, 0, 0.5)",
        },
    };
}

function createProjectJsonData({ name, audioFilePath = "", imageFilePath = "", scriptFiles = [] }) {
    const result = getDefaultJsonData();
    result.name = name;
    result.audioFilePath = audioFilePath;
    result.imageSrtPath = "";
    result.imageFilePath = imageFilePath;
    result.scriptFiles = scriptFiles.length
        ? scriptFiles
        : [defaultSrtFileShape({ filePath: getDefaultGeneratedTrackName(name), inlineData: [] })];
    result.styles = {
        "default-style-1": getDefaultStyleData(),
    };
    normalizeStyleColors(result.styles);
    return result;
}

function defaultSrtFileShape({ filePath = "", name = filePath, inlineData = null, defaultStyle = "default-style-1" }) {
    return {
        filePath,
        name,
        defaultStyle,
        x: 80,
        y: 780,
        maxWidth: 1760,
        maxHeight: 260,
        boxAlignX: 50,
        boxAlignY: 50,
        textRotate: "horizontal-tb",
        textAlign: "center",
        ...(inlineData ? { inlineData } : {}),
    };
}

export function createSubtitleScriptFile({ filePath, name = filePath, defaultStyle = "default-style-1" }) {
    return defaultSrtFileShape({ filePath, name, inlineData: null, defaultStyle });
}

export function createBlankSubtitleClip(duration = 0) {
    const endTime = Math.max(1, Number(duration) || 0);
    return {
        startTimeStr: "00:00:00,000",
        endTimeStr: convSecToStr(endTime),
        startTime: 0,
        endTime,
        text: "",
        ref: {},
    };
}

export function createSubtitleMediaTrack({ id, name, filePath, data, defaultStyle = "default-style-1" }) {
    return {
        id,
        name,
        file_path: filePath,
        height: 40,
        default_class: defaultStyle,
        isImageTrack: false,
        loadStatus: "loaded",
        loadError: null,
        data,
    };
}

function ensureProjectHasEditableTrack(data) {
    if (data.scriptFiles?.length) return data;
    const baseName = getBaseName(data.name ?? "sample");
    return {
        ...data,
        scriptFiles: [defaultSrtFileShape({ filePath: getDefaultGeneratedTrackName(baseName), inlineData: [] })],
    };
}

export function getSentenceJsonData(filename, text, options = {}) {
    const inlineData = parseSentenceJsonSubtitle(text, true);
    if (!inlineData?.some((row) => Array.isArray(row.sentences) || typeof row.text === "string")) {
        return null;
    }

    const baseName = getBaseName(filename);
    return createProjectJsonData({
        name: filename,
        audioFilePath: options.audioFilePath ?? `${baseName}.mp3`,
        imageFilePath: options.imageFilePath ?? "",
        scriptFiles: [defaultSrtFileShape({
            filePath: filename,
            name: filename,
        })],
    });
}

export async function saveJsonFile(dirHandle, name = "sample.vc_json", jsondata, subdir = null) {
    if (!dirHandle) return false;
    let writable;
    let targetDirHandle;
    let created = false;
    try {
        const text = JSON.stringify({
            ...stripInlineDataFromVcJson(jsondata),
            name,
        }, null, 2);
        // 保存先ディレクトリの取得
        targetDirHandle = subdir
            ? await dirHandle.getDirectoryHandle(subdir, { create: true })
            : dirHandle;

        let fileHandle;
        try {
            fileHandle = await targetDirHandle.getFileHandle(name);
        } catch (err) {
            if (err.name !== "NotFoundError") throw err;
            fileHandle = await targetDirHandle.getFileHandle(name, { create: true });
            created = true;
        }
        writable = await fileHandle.createWritable();
        await writable.write(text);
        await writable.close();

        console.log(`保存完了: ${subdir ? `${subdir}/` : ""}${name}`);
        return true;
    } catch (err) {
        try { await writable?.abort(); } catch { /* Preserve the save failure. */ }
        if (created) {
            try { await targetDirHandle.removeEntry(name); } catch { /* Leave cleanup failure visible on retry. */ }
        }
        return false;
    }
}



export async function getJsonDataList(dirHandle) {
    const result = [];
    const entries = [];
    for await (const entry of dirHandle.values()) {
        entries.push(entry);
    }
    const fileEntries = getSortedFileEntries(entries);

    let files = fileEntries.filter((entry) => entry.name.endsWith(".vc_json"));
    for (const entry of files) {
        const file = await entry.getFile();
        const text = await file.text();
        const data = getVCJsonData(text, file.name);
        result.push(data);
    }
    if (result.length) return result;

    files = fileEntries.filter((entry) => entry.name.endsWith(".voice_json"));
    for (const entry of files) {
        const file = await entry.getFile();
        const text = await file.text();
        const data = getVoiceJsonData(file.name, text);
        result.push(data);
    }

    if (result.length) return result;

    const audioEntry = fileEntries.find((entry) => hasExtension(entry.name, AUDIO_EXTENSIONS));
    const imageEntry = fileEntries.find((entry) => hasExtension(entry.name, IMAGE_EXTENSIONS));
    const jsonSubtitleEntries = fileEntries.filter((entry) => entry.name.endsWith(".json"));

    for (const entry of jsonSubtitleEntries) {
        const file = await entry.getFile();
        const text = await file.text();
        const data = getSentenceJsonData(file.name, text, {
            audioFilePath: audioEntry?.name ?? "",
            imageFilePath: imageEntry?.name ?? "",
        });
        if (data) {
            result.push(markAutoGenerated(data, getGeneratedVcJsonName(getBaseName(file.name))));
        }
    }
    if (result.length) return result;

    const srtEntries = fileEntries.filter((entry) => entry.name.endsWith(".srt"));
    if (srtEntries.length || audioEntry || imageEntry) {
        const baseName = getBaseName(audioEntry?.name ?? srtEntries[0]?.name ?? imageEntry?.name ?? dirHandle.name ?? "sample");
        const scriptFiles = srtEntries.length
            ? srtEntries.map((entry) => defaultSrtFileShape({ filePath: entry.name, name: entry.name }))
            : [defaultSrtFileShape({ filePath: getDefaultGeneratedTrackName(baseName), inlineData: [] })];

        result.push(markAutoGenerated(createProjectJsonData({
            name: baseName,
            audioFilePath: audioEntry?.name ?? "",
            imageFilePath: imageEntry?.name ?? "",
            scriptFiles,
        }), getGeneratedVcJsonName(baseName)));
    }
    return result;

}


/*
*　　-- srtdata処理関連 --
*　　字幕ファイル・字幕データ関連の処理
*/
export function getDefaultSrtFiles() {
    return {
        name: "default",
        file_path: '',
        default_class: 'default1',
        height: 50,
        data: [
            {
                id: 1,
                startTimeStr: "00:00:00,000",
                endTimeStr: "00:00:18,330",
                startTime: 0,
                endTime: 18.33,
                text: ''
            }
        ]
    };
}



// SRTファイルをパースしてデータ配列に変換する関数
export function parseSrt(srt_text) {
    if (srt_text === null) return [];

    //srtファイルの構造の記述
    //  "通し番号"
    //  "時間 --> 時間" 
    //  "文章 + 改行2回(もしくは末尾)"
    const blockPattern = /(?:^|\r?\n\r?\n)(\d+)\r?\n([\d:,]+)\s-{2}>\s([\d:,]+)\r?\n([\s\S]*?)(?=\r?\n\r?\n\d+\r?\n|$)/g;

    const srtList = [];
    let parsedEnd = 0;
    for (const match of srt_text.matchAll(blockPattern)) {
        if (srt_text.slice(parsedEnd, match.index).trim()) throw new Error("Invalid SRT block");
        srtList.push(parseSrtBlock({
            id: match[1],
            start: match[2],
            end: match[3],
            body: match[4],
        }));
        parsedEnd = match.index + match[0].length;
    }
    if (srt_text.slice(parsedEnd).trim()) throw new Error("Invalid SRT data");
    if (!srtList.length) return [];
    return srtList ? normalizeSrtItems(srtList) : [];
};

/**
 * SRT データの最後のクリップの endTime が duration より短い場合に duration まで引き伸ばす
 * @param {Array} srtData
 * @param {number} duration 秒
 */
export function extendLastClipToDuration(srtData, duration) {
    if (!srtData || srtData.length === 0 || !duration) return;
    const last = srtData[srtData.length - 1];
    if (last.endTime < duration) {
        last.endTime = duration;
        last.endTimeStr = convSecToStr(duration);
    }
}


// SRTファイルのブロックをデータに変換する関数
export function parseSrtBlock(part) {
    let id;
    let start;
    let end;
    let text;
    if (typeof part === "string") {
        const match = part.match(/^(\d+)\r?\n([\d:,]+)\s-{2}>\s([\d:,]+)\r?\n?([\s\S]*)$/);
        if (!match) return null;
        id = parseInt(match[1]);
        start = match[2];
        end = match[3];
        text = match[4] ?? "";
    } else {
        id = parseInt(part.id);
        start = part.start;
        end = part.end;
        text = part.body ?? "";
    }
    const parsedBody = parseSrtBodyText(text);

    const entry = {
        startTimeStr: start,
        endTimeStr: end,
        startTime: convStrToSec(start),
        endTime: convStrToSec(end),
        text: parsedBody.text,
        ...(parsedBody.sentences.length > 1 ? { sentences: parsedBody.sentences } : {}),
        ref: {}
    };
    return entry;
}





export async function saveSrtFile(dirHandle, name, data, subdir = null) {
    if (!dirHandle) return false;

    try {
        const text = combineToSRT(data);
        // 保存先ディレクトリの取得
        const targetDirHandle = subdir
            ? await dirHandle.getDirectoryHandle(subdir, { create: true })
            : dirHandle;

        // 書き込むファイルのハンドル
        const fileHandle = await targetDirHandle.getFileHandle(name, { create: true });
        const writable = await fileHandle.createWritable();

        // jsondata.name を name に置き換えたコピーを作成
        const nameWithoutExt = name;

        await writable.write(text);
        await writable.close();

        console.log(`保存完了: ${subdir ? `${subdir}/` : ""}${name}`);
        return true;
    } catch (err) {
        console.error("保存失敗:", err);
        return false;
    }
}

function serializeSentenceJsonSubtitle(data) {
    return JSON.stringify((data ?? []).map((item) => {
        const sentences = Array.isArray(item?.sentences) && item.sentences.length
            ? item.sentences.map((sentence) => normalizeInlineNewlines(sentence).trim()).filter(Boolean)
            : splitTextToSentences(getSrtItemText(item));
        return {
            start: getPersistedTime(item, "start"),
            end: getPersistedTime(item, "end"),
            sentences,
            ...copyClipBlockExtensions(item),
        };
    }), null, 2);
}

function getSubtitlePathParts(path) {
    const normalizedPath = String(path || "").replace(/\\/g, "/");
    const parts = normalizedPath.split("/");
    if (parts.some((part) => !part || part === "." || part === ".." || /[:*?"<>|]/.test(part))) {
        throw new Error("Invalid relative subtitle path");
    }
    return parts;
}

async function saveTextFileByPath(dirHandle, path, text, createOnly = false) {
    if (!dirHandle) return false;
    let writable;
    let created = false;
    let targetDirHandle = dirHandle;
    let fileName;
    try {
        const parts = getSubtitlePathParts(path);
        fileName = parts.pop();
        for (const part of parts) {
            targetDirHandle = await targetDirHandle.getDirectoryHandle(part, { create: true });
        }
        if (createOnly) {
            try {
                await targetDirHandle.getFileHandle(fileName);
                return false;
            } catch (err) {
                if (err.name !== "NotFoundError") throw err;
            }
        }
        const fileHandle = await targetDirHandle.getFileHandle(fileName, { create: true });
        created = createOnly;
        writable = await fileHandle.createWritable();
        await writable.write(text);
        await writable.close();
        return true;
    } catch (err) {
        try { await writable?.abort(); } catch { /* Preserve the original failure. */ }
        if (created) {
            try { await targetDirHandle.removeEntry(fileName); } catch { /* Never remove the parent directory. */ }
        }
        return false;
    }
}

function serializeSubtitle(path, data) {
    return path.toLowerCase().endsWith(".json")
        ? serializeSentenceJsonSubtitle(data)
        : combineToSRT(data);
}

export async function saveSubtitleFile(dirHandle, path, data, options = {}) {
    if (options.loadStatus !== undefined && options.loadStatus !== "loaded") return false;
    if (!path || !Array.isArray(data)) return false;
    try {
        return await saveTextFileByPath(dirHandle, path, serializeSubtitle(path, data));
    } catch {
        return false;
    }
}

export async function saveSubtitleTrack(dirHandle, track) {
    if (track?.loadStatus !== "loaded" || !track.file_path) return false;
    return saveSubtitleFile(dirHandle, track.file_path, track.data, { loadStatus: track.loadStatus });
}

// Serialize creates across handles so repeated clicks cannot pass the same existence check.
// File System Access has no atomic exclusive-create primitive against external writers.
let subtitleCreationQueue = Promise.resolve();
export async function createSubtitleFile(dirHandle, path, data) {
    const create = async () => {
        if (!path || !Array.isArray(data)) return false;
        try {
            return await saveTextFileByPath(dirHandle, path, serializeSubtitle(path, data), true);
        } catch {
            return false;
        }
    };
    const result = subtitleCreationQueue.then(create);
    subtitleCreationQueue = result.then(() => undefined, () => undefined);
    return result;
}

// The caller must only pass paths successfully created by its current operation.
export async function removeCreatedSubtitleFile(dirHandle, path) {
    if (!dirHandle) return false;
    try {
        const parts = getSubtitlePathParts(path);
        const name = parts.pop();
        let directory = dirHandle;
        for (const part of parts) directory = await directory.getDirectoryHandle(part);
        await directory.getFileHandle(name);
        await directory.removeEntry(name);
        return true;
    } catch {
        return false;
    }
}

function getPersistedTime(item, edge) {
    const seconds = item[`${edge}Time`] ?? convStrToSec(item[`${edge}TimeStr`]);
    if (!Number.isFinite(seconds) || seconds < 0) throw new Error("Invalid subtitle time");
    return convSecToStr(seconds);
}


export function combineToSRT(data) {
    if (data.some(hasClipBlockExtensions)) {
        throw new TypeError("SRT cannot preserve subtitle block extensions; save as JSON");
    }
    let srtText = "";
    let id = 1;
    for (const srtPart of data) {
        srtText += id + '\r\n';
        srtText += getPersistedTime(srtPart, "start") + ' --> ' + getPersistedTime(srtPart, "end");
        if (getSrtItemText(srtPart)) {
            srtText += '\r\n' + serializeSrtBodyText(srtPart);
            if (srtPart.text !== "\r\n") srtText += '\r\n\r\n';
        } else {
            srtText += '\r\n\u3000\r\n\r\n';
        }
        id++;
    }
    return srtText;
}


export function getCurrentText(data, time) {
    // data は normalizeSrtItems 済み（startTime 昇順・連続、endTime も昇順）である前提。
    // endTime 昇順を利用し「endTime >= time となる最も手前のクリップ」を二分探索で求める。
    // これは線形走査の「最初に一致したクリップを返す（継ぎ目では手前優先）」と同じ結果になり、
    // 再生中に毎フレーム呼ばれる探索を O(n) → O(log n) に下げる。
    let lo = 0;
    let hi = data.length;
    while (lo < hi) {
        const mid = (lo + hi) >> 1;
        if (data[mid].endTime >= time) hi = mid;
        else lo = mid + 1;
    }
    const entry = data[lo];
    if (entry && time >= entry.startTime && time <= entry.endTime) {
        const primaryText = getSrtItemText(entry);
        const text = primaryText.trim() ? primaryText
            : getClipBlocks(entry).slice(1).map(({ body }) => getSrtItemText(body)).find((value) => value.trim()) ?? primaryText;
        return { text, entry, index: lo };
    }
    return { text: "", entry: null, index: -1 }; // 一致なし
}




export const calculate_shadow = ({ enable, steps, offsetX, offsetY, size, color, blur }) => {
    if (!enable) return "none";
    const shadowSize = size;
    const shadowBlur = blur;
    const shadowColor = color;

    let textShadow = "none";
    if (steps == 1) {
        textShadow = `${offsetX}px ${offsetY}px ${shadowBlur}px ${shadowColor}`;
    } else {
        const outerShadows = createShadowDirections(steps).map(
            ([dx, dy]) =>
                `${offsetX + dx * shadowSize}px ${offsetY + dy * shadowSize}px ${shadowBlur}px ${shadowColor}`
        );
        textShadow = [...outerShadows].join(", ");
    }

    return textShadow;
}

const createShadowDirections = (steps, offset = 0) => {
    steps = Math.ceil(steps);
    const angleStep = (2 * Math.PI) / steps;
    return Array.from({ length: steps }, (_, i) => {
        const angle = i * angleStep + offset;
        return [Math.round(Math.cos(angle)), Math.round(Math.sin(angle))];
    });
};



export function convertToStyledSpans(defaultStyleName, text) {
    const result = [];
    const tagPattern = /<(\w+)>([\s\S]*?)<\/>/g;
    let lastIndex = 0;

    for (const match of text.matchAll(tagPattern)) {
        const [fullMatch, styleName, content] = match;
        const start = match.index;

        // タグの前の通常テキスト
        if (start > lastIndex) {
            const normal = text.slice(lastIndex, start);
            result.push({ style: defaultStyleName, text: normal });
        }

        // タグ部分
        result.push({ style: styleName, text: content });

        lastIndex = start + fullMatch.length;
    }

    // 残り
    if (lastIndex < text.length) {
        result.push({ style: defaultStyleName, text: text.slice(lastIndex) });
    }

    return result;
}





function normalizeSrtItems(srtItems) {
    const sorted = [...srtItems].sort((a, b) => a.startTime - b.startTime);
    const normalized = [];

    for (let i = 0; i < sorted.length; i++) {
        const curr = { ...sorted[i] };
        validateClipBlocks(curr);
        const prev = normalized[normalized.length - 1];

        if (!prev) {
            if (curr.startTime > 0) {
                normalized.push({
                    startTime: 0,
                    endTime: curr.startTime,
                    startTimeStr: "00:00:00,000",
                    endTimeStr: convSecToStr(curr.startTime),
                    text: "　",
                    ref: {}
                });
            }
        } else {
            // 被り解消
            if (curr.startTime < prev.endTime) {
                prev.endTime = curr.startTime;
                prev.endTimeStr = convSecToStr(prev.endTime);
            }

            // 空白時間 → text: "" を挿入
            if (curr.startTime > prev.endTime) {
                normalized.push({
                    startTime: prev.endTime,
                    endTime: curr.startTime,
                    startTimeStr: convSecToStr(prev.endTime),
                    endTimeStr: convSecToStr(curr.startTime),
                    text: "　",
                    ref: {}
                });
            }
        }

        // 時間逆転防止（安全対策）
        if (curr.endTime < curr.startTime) {
            curr.endTime = curr.startTime;
        }

        // str更新
        curr.startTimeStr = convSecToStr(curr.startTime);
        curr.endTimeStr = convSecToStr(curr.endTime);

        // "　" 連続 → 結合処理
        if (
            prev &&
            !hasClipBlockExtensions(prev) &&
            !hasClipBlockExtensions(curr) &&
            isOnlyFullWidthSpace(prev.text) &&
            isOnlyFullWidthSpace(curr.text)
        ) {
            // prevのendを伸ばす
            prev.endTime = curr.endTime;
            prev.endTimeStr = convSecToStr(curr.endTime);
        } else {
            normalized.push(curr);
        }
    }

    return normalized;
}

function isOnlyFullWidthSpace(text) {
    return typeof text === "string" && text.trim() === "" && /　/.test(text);
}
