import { getFileFromPath, convSecToStr, convStrToSec, COLOR } from "./util";

const AUDIO_EXTENSIONS = [".mp3", ".wav", ".m4a", ".aac", ".flac", ".ogg"];
const IMAGE_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"];
const AUTO_GENERATED_VC_JSON = Symbol("autoGeneratedVcJson");

function hasExtension(name, extensions) {
    const lower = name.toLowerCase();
    return extensions.some((ext) => lower.endsWith(ext));
}

function markAutoGenerated(data, vcJsonName) {
    Object.defineProperty(data, AUTO_GENERATED_VC_JSON, {
        value: vcJsonName,
        enumerable: false,
    });
    return data;
}

export function getAutoGeneratedVcJsonName(data) {
    return data?.[AUTO_GENERATED_VC_JSON] ?? null;
}

function getSortedFileEntries(entries) {
    return entries
        .filter((entry) => entry.kind === "file")
        .sort((a, b) => a.name.localeCompare(b.name, "ja"));
}

function getBaseName(filename) {
    return filename.replace(/\.[^/.]+$/, "");
}

function getGeneratedVcJsonName(baseName) {
    return `${baseName || "sample"}.vc_json`;
}

function getDefaultGeneratedTrackName(baseName) {
    return `${baseName || "sample"}.srt`;
}


/*
*　　-- media処理関連 --
*　　vc_jsonファイル単位のメディアデータ（audio、img、srtなど）関連の処理
*/
export function getDefaultMedia(){
    return {
        name: "メディアなし",
        image_data: { currentId: 0, currentImage: null, currentImagePath: null, size: { x: 0, y: 0 } },
        srt_data: [],
        isAudio: true,
        isPlaying: false,
        duration: 0,
        playbackRate: 1,
        volume: 0.5,
      }
}

function cloneSrtData(data) {
    return (data ?? []).map((item) => ({ ...item, ref: item.ref ?? {} }));
}

function normalizeInlineNewlines(text) {
    return String(text ?? "").replace(/\r(?!\n)/g, "\n");
}

function splitTextToSentences(text) {
    const lines = normalizeInlineNewlines(text).replace(/\r\n/g, "\n").split("\n");
    const sentences = [];
    let current = [];

    for (const line of lines) {
        if (isParagraphSeparatorLine(line)) {
            if (current.length) {
                sentences.push(current.join("\n"));
                current = [];
            }
            continue;
        }
        current.push(line);
    }
    if (current.length) sentences.push(current.join("\n"));

    return sentences
        .map((sentence) => sentence.trim())
        .filter((sentence) => sentence.length > 0);
}

function joinSentencesWithParagraphBreak(sentences) {
    return (sentences ?? []).map((sentence) => normalizeInlineNewlines(sentence)).join("\r\n");
}

function isParagraphSeparatorLine(line) {
    return String(line ?? "").trim() === "" || /^[　]+$/.test(String(line ?? ""));
}

function isSrtParagraphSeparatorLine(line) {
    return isParagraphSeparatorLine(line);
}

function parseSrtBodyText(body) {
    const lines = String(body ?? "").replace(/\r\n|\r|\n/g, "\n").replace(/\n+$/g, "").split("\n");
    const sentences = [];
    let current = [];

    for (const line of lines) {
        if (isSrtParagraphSeparatorLine(line)) {
            if (current.length) {
                sentences.push(current.join("\n"));
                current = [];
            }
            continue;
        }
        current.push(line);
    }
    if (current.length) sentences.push(current.join("\n"));

    const text = sentences.length ? joinSentencesWithParagraphBreak(sentences) : "";
    return { text, sentences };
}

function serializeSrtBodyText(item) {
    const sentences = Array.isArray(item?.sentences) && item.sentences.length
        ? item.sentences
        : splitTextToSentences(getSrtItemText(item));
    return sentences
        .map((sentence) => normalizeInlineNewlines(sentence).replace(/\r\n/g, "\n").replace(/\n/g, "\r\n"))
        .join("\r\n　\r\n");
}

export function getSrtItemText(item) {
    if (!item) return "";
    if (Array.isArray(item.sentences)) {
        return joinSentencesWithParagraphBreak(item.sentences);
    }
    return normalizeInlineNewlines(item.text ?? "");
}

export function setSrtItemText(item, text) {
    if (!item) return;
    const normalized = normalizeInlineNewlines(text);
    const sentences = splitTextToSentences(normalized);
    if (sentences.length > 1) {
        item.sentences = sentences;
        item.text = joinSentencesWithParagraphBreak(sentences);
    } else {
        delete item.sentences;
        item.text = sentences[0] ?? normalized;
    }
}

export function setSrtItemSentence(item, index, text) {
    if (!item || !Array.isArray(item.sentences)) return;
    item.sentences[index] = normalizeInlineNewlines(text);
    item.text = joinSentencesWithParagraphBreak(item.sentences);
}

function getDurationFromSrtData(tracks) {
    return Math.max(0, ...tracks.flatMap((track) => (track.data ?? []).map((item) => item.endTime || 0)));
}

function serializeJsonSrtItem(item) {
    const sentences = Array.isArray(item?.sentences) && item.sentences.length
        ? item.sentences.map((sentence) => normalizeInlineNewlines(sentence).trim()).filter(Boolean)
        : splitTextToSentences(item?.text ?? "");
    const text = sentences.length > 1 ? joinSentencesWithParagraphBreak(sentences) : normalizeInlineNewlines(item?.text ?? sentences[0] ?? "");
    return {
        ...item,
        text,
        ...(sentences.length > 1 ? { sentences } : {}),
    };
}

export function syncJsonDataFromMedia(jsonData, media) {
    if (!jsonData?.scriptFiles || !media?.srt_data) return jsonData;
    const editableTracks = media.srt_data.filter((track) => !track.isImageTrack);
    return {
        ...jsonData,
        scriptFiles: jsonData.scriptFiles.map((scriptFile, index) => {
            const track = editableTracks.find((item) => item.id === index) ?? editableTracks[index];
            if (!track?.data) return scriptFile;
            const { inlineData, ...scriptFileWithoutText } = scriptFile;
            if (scriptFile.filePath) return scriptFileWithoutText;
            return {
                ...scriptFileWithoutText,
                inlineData: track.data.map(serializeJsonSrtItem),
            };
        }),
    };
}

function stripInlineDataFromVcJson(jsondata) {
    if (!jsondata?.scriptFiles) return jsondata;
    const { srtFiles, jsonFiles, ...restJsonData } = jsondata;
    return {
        ...restJsonData,
        scriptFiles: jsondata.scriptFiles.map((scriptFile) => {
            const { inlineData, ...rest } = scriptFile;
            return rest;
        }),
    };
}

async function tryGetFileFromPath(dirHandle, path) {
    try {
        return await getFileFromPath(dirHandle, path);
    } catch (err) {
        console.warn("ファイル読み込みスキップ:", path, err);
        return null;
    }
}

function makeTrack({ id, name, filePath = "", data = [], isImageTrack = false, defaultStyle = "default-style-1" }) {
    const normalizedData = normalizeSrtItems(cloneSrtData(data));
    return {
        id,
        name,
        file_path: filePath,
        height: 40,
        default_class: defaultStyle,
        isImageTrack,
        data: normalizedData,
    };
}

export async function getMedia(data,dirHandle) {
    if (!dirHandle || !data || data.name === "dummy") {
      return getDefaultMedia();
    }
    let audio = null;
    let audioUrl = null;
    let duration = 0;
    const audiofile = await tryGetFileFromPath(dirHandle, data.audioFilePath);
    if (audiofile) {
      audioUrl = URL.createObjectURL(audiofile);
      audio = new Audio(audioUrl);
      await new Promise((resolve) => {
        audio.onloadedmetadata = resolve;
        audio.onerror = resolve;
      });
      duration = Number.isFinite(audio.duration) ? audio.duration : 0;
      const initialSeek = data.seekTime ?? 0;
      audio.currentTime = duration ? Math.min(initialSeek, duration) : initialSeek;
    }

    const srtDatafiles = [];
    for (const [i, script] of (data.scriptFiles ?? []).entries()) {
      let srtData = cloneSrtData(script.inlineData);
      let srtName = script.name || script.filePath || `${data.name}-${i + 1}.srt`;
      if (!srtData.length && script.filePath) {
        const scriptFile = await tryGetFileFromPath(dirHandle, script.filePath);
        if (scriptFile) {
          srtName = scriptFile.name;
          const text = await scriptFile.text();
          try {
            srtData = script.filePath.toLowerCase().endsWith(".json")
              ? parseSentenceJsonSubtitle(text)
              : parseSrt(text);
          } catch (err) {
            console.warn("字幕ファイルの解析に失敗しました:", script.filePath, err);
            srtData = [];
          }
        }
      }
      extendLastClipToDuration(srtData, duration);
      srtDatafiles.push(makeTrack({
        id: i,
        name: srtName,
        filePath: script.filePath,
        data: srtData,
        defaultStyle: script.defaultStyle ?? script.default_class ?? "default-style-1",
      }));
    }

    if (!duration) duration = getDurationFromSrtData(srtDatafiles);

    let imageURL = null;
    let imagePath = null;
    if (data.imageSrtPath) {
      const imgSrtFile = await tryGetFileFromPath(dirHandle, data.imageSrtPath);
      if (imgSrtFile) {
        const imgSrtText = await imgSrtFile.text();
        const imgSrtparts = parseSrt(imgSrtText);
        extendLastClipToDuration(imgSrtparts, duration);
        srtDatafiles.push(makeTrack({
          id: srtDatafiles.length,
          name: imgSrtFile.name,
          filePath: data.imageSrtPath,
          data: imgSrtparts,
          isImageTrack: true,
        }));
        imagePath = imgSrtparts[0]?.text?.replace(/\\/g, "/") ?? null;
      }
    }
    if (!imagePath && data.imageFilePath) {
      imagePath = data.imageFilePath.replace(/\\/g, "/");
    }
    if (imagePath) {
      const imageFile = await tryGetFileFromPath(dirHandle, imagePath);
      if (imageFile) imageURL = URL.createObjectURL(imageFile);
    }

    return {
      name: data.name,
      audio,
      audioUrl,
      image_data: {
        currentId: 0,
        currentImage: imageURL,
        currentImagePath: imagePath,
        size: { x: 0, y: 0 },
      },
      srt_data: srtDatafiles,
      isAudio: !!audio,
      isPlaying: false,
      duration,
      playbackRate: 1,   // 呼び出し元で現在値に上書きされる
      volume: 0.5,       // 同上
    };
  }


/*
*　　-- media処理関連 --
*　　vc_jsonファイル単位のメディアデータ（audio、img、srtなど）関連の処理
*/
export function getDefaultJsonData() {
    return {
        name: "dummy",
        seekTime: 0,
        audioFilePath: '',
        imageSrtPath: '',
        scriptFiles: [
            {
                filePath: '',
                defaultStyle: 'dummy',
                x: 100,
                y: 100,
                maxWidth: 500,
                maxHeight: 500,
                boxAlignX: 0,
                boxAlignY: 0,
                textRotate: "horizontal-tb",
                textAlign: "left"
            }
        ],
        styles: {
            dummy: {
                font: "りいポップ角",
                fontSize: 30,
                textColor: "rgba(0, 0, 0,1)",
                letterSpace: 0,
                lineSpace: 10,
                fontStyle: "italic",
                fontWeight: "bold",
                isItalic: false,
                outline1: {
                    enable: true,
                    size: 7,
                    color: "rgba(177, 34, 34, 0.95)"
                },
                outline2: {
                    enable: true,
                    offsetX: 0,
                    offsetY: 0,
                    size: 5,
                    color: "rgba(32, 32, 32, 0.8)"
                },
                shadow: {
                    enable: true,
                    steps: 8,
                    offsetX: 0,
                    offsetY: 0,
                    size: 10,
                    color: "rgba(170, 0, 119, 0.1)",
                    blur: 16
                }
            }
        }
    };
}
export function getVCJsonData(text, filename = "sample.vc_json") {
    const raw = JSON.parse(text);
    const def = getDefaultJsonData();
    const rawStyles = Object.entries(raw.styles || {});
    const rawScriptFiles = raw.scriptFiles || raw.srtFiles || raw.jsonFiles || [];
    const { srtFiles, jsonFiles, ...rawWithoutLegacyScriptFiles } = raw;

    const result = {
        ...def,
        ...rawWithoutLegacyScriptFiles,
        name: raw.name || filename,
        scriptFiles: rawScriptFiles.map((script, i) => ({
            ...def.scriptFiles[0],
            ...script
        })),
        styles: rawStyles.length
            ? Object.fromEntries(rawStyles.map(([key, style]) => {
                const styleData = style ?? {};
                return [key, {
                    ...def.styles.dummy,
                    ...styleData,
                    outline1: { ...def.styles.dummy.outline1, ...styleData.outline1 },
                    outline2: { ...def.styles.dummy.outline2, ...styleData.outline2 },
                    shadow:   { ...def.styles.dummy.shadow,   ...styleData.shadow   }
                }];
            }))
            : def.styles
    };

    return ensureProjectHasEditableTrack(result);
}



export function getVoiceJsonData(filename, text) {
    const raw = JSON.parse(text);
    const result = getDefaultJsonData();

    result.name = filename;
    result.seekTime = raw.seekTime || 0;
    result.audioFilePath = raw.audioFile || '';
    result.imageSrtPath = raw.imageSRT || '';
    result.scriptFiles = [];
    // @ts-ignore
    result.styles = {};

    // 各SRTファイルを処理
    raw.srtFiles?.forEach((srt, index) => {
        const styleKey = `default-style-${index + 1}`;

        // スタイル部分を切り出し
        const {
            max_width, max_height, isVertical,
            textAlignSelect, verticalAlignSelect,
            font, fontSize, textColor,
            letter_space, line_space,
            isBold, isItalic,
            outline1, outline2, shadow,
            ...layoutProps
        } = srt;

        const fixColorObject = (obj) => {
            const { color, opacity, ...rest } = obj;
            return {
                ...rest,
                color: COLOR.mergeColorAndOpacity({ color, opacity:1-opacity })
            };
        };
        
        const outline1Fixed = fixColorObject(outline1);
        const outline2Fixed = fixColorObject({ ...outline2 });
        const shadowFixed = fixColorObject({
            ...shadow,
            steps: 1,
            offsetX: 0,
            offsetY: 0
        });

        const align = textAlignSelect == 1 ? "left" : textAlignSelect == 2 ? "center" : "right";
        // scriptFilesに1つ追加（配列形式）
        result.scriptFiles.push({
            ...layoutProps,
            maxWidth: max_width,
            maxHeight: max_height,
            defaultStyle: styleKey,
            textAlign: align,
            textRotate: isVertical ? "vertical-rl" : "horizontal-tb",

        });

        const fontStyle = isItalic ? "italic" : "normal";
        const fontWeight = isBold ? "bold" : "normal";

        // stylesにスタイル登録
        result.styles[styleKey] = {
            font, fontSize, textColor,
            letterSpace: letter_space,
            lineSpace: line_space,
            fontWeight, fontStyle,
            outline1:outline1Fixed, 
            outline2:outline2Fixed, 
            shadow:shadowFixed
        };
    });

    return ensureProjectHasEditableTrack(result);
}

function joinSentences(sentences) {
    return (sentences ?? [])
        .map((sentence) => String(sentence ?? "").trim())
        .filter((sentence) => sentence.length > 0)
        .join("\r\n");
}

function parseSentenceJsonSubtitle(text) {
    const raw = JSON.parse(text);
    const rows = Array.isArray(raw) ? raw : raw.items;
    if (!Array.isArray(rows)) return [];
    return rows.map((row) => ({
        startTimeStr: row.start,
        endTimeStr: row.end,
        startTime: convStrToSec(row.start),
        endTime: convStrToSec(row.end),
        sentences: (row.sentences ?? []).map((sentence) => normalizeInlineNewlines(sentence).trim()).filter((sentence) => sentence.length > 0),
        text: joinSentences(row.sentences),
        ref: {},
    }));
}

function getDefaultStyleData() {
    const def = getDefaultJsonData();
    return {
        ...def.styles.dummy,
        fontSize: 42,
        textColor: "rgba(255, 255, 255,1)",
        fontStyle: "normal",
        fontWeight: "bold",
        lineSpace: 10,
        outline1: {
            ...def.styles.dummy.outline1,
            size: 5,
            color: "rgba(0, 0, 0, 0.95)",
        },
        outline2: {
            ...def.styles.dummy.outline2,
            enable: false,
        },
        shadow: {
            ...def.styles.dummy.shadow,
            enable: true,
            size: 2,
            blur: 6,
            color: "rgba(0, 0, 0, 0.5)",
        },
    };
}

function createProjectJsonData({ name, audioFilePath = "", imageFilePath = "", scriptFiles = [] }) {
    const result = getDefaultJsonData();
    result.name = name;
    result.audioFilePath = audioFilePath;
    result.imageSrtPath = "";
    result.imageFilePath = imageFilePath;
    result.scriptFiles = scriptFiles.length
        ? scriptFiles
        : [defaultSrtFileShape({ filePath: getDefaultGeneratedTrackName(name), inlineData: [] })];
    result.styles = {
        "default-style-1": getDefaultStyleData(),
    };
    return result;
}

function defaultSrtFileShape({ filePath = "", name = filePath, inlineData = null, defaultStyle = "default-style-1" }) {
    return {
        filePath,
        name,
        defaultStyle,
        x: 80,
        y: 780,
        maxWidth: 1760,
        maxHeight: 260,
        boxAlignX: 50,
        boxAlignY: 50,
        textRotate: "horizontal-tb",
        textAlign: "center",
        ...(inlineData ? { inlineData } : {}),
    };
}

export function createSubtitleScriptFile({ filePath, name = filePath, defaultStyle = "default-style-1" }) {
    return defaultSrtFileShape({ filePath, name, inlineData: null, defaultStyle });
}

export function createBlankSubtitleClip(duration = 0) {
    const endTime = Math.max(1, Number(duration) || 0);
    return {
        startTimeStr: "00:00:00,000",
        endTimeStr: convSecToStr(endTime),
        startTime: 0,
        endTime,
        text: "",
        ref: {},
    };
}

export function createSubtitleMediaTrack({ id, name, filePath, data, defaultStyle = "default-style-1" }) {
    return {
        id,
        name,
        file_path: filePath,
        height: 40,
        default_class: defaultStyle,
        isImageTrack: false,
        data,
    };
}

function ensureProjectHasEditableTrack(data) {
    if (data.scriptFiles?.length) return data;
    const baseName = getBaseName(data.name ?? "sample");
    return {
        ...data,
        scriptFiles: [defaultSrtFileShape({ filePath: getDefaultGeneratedTrackName(baseName), inlineData: [] })],
    };
}

export function getSentenceJsonData(filename, text, options = {}) {
    const inlineData = parseSentenceJsonSubtitle(text);
    if (!inlineData.some((row) => Array.isArray(row.sentences))) {
        return null;
    }

    const baseName = getBaseName(filename);
    return createProjectJsonData({
        name: filename,
        audioFilePath: options.audioFilePath ?? `${baseName}.mp3`,
        imageFilePath: options.imageFilePath ?? "",
        scriptFiles: [defaultSrtFileShape({
            filePath: filename,
            name: filename,
        })],
    });
}

export async function saveJsonFile(dirHandle, name = "sample.vc_json", jsondata, subdir = null) {
    if (!dirHandle) return false;

    try {
        // 保存先ディレクトリの取得
        const targetDirHandle = subdir
            ? await dirHandle.getDirectoryHandle(subdir, { create: true })
            : dirHandle;

        // 書き込むファイルのハンドル
        const fileHandle = await targetDirHandle.getFileHandle(name, { create: true });
        const writable = await fileHandle.createWritable();

        // jsondata.name を name に置き換えたコピーを作成
        const nameWithoutExt = name;
        const dataToSave = {
            ...stripInlineDataFromVcJson(jsondata),
            name: nameWithoutExt,
        };

        await writable.write(JSON.stringify(dataToSave, null, 2));
        await writable.close();

        console.log(`保存完了: ${subdir ? `${subdir}/` : ""}${name}`);
        return true;
    } catch (err) {
        console.error("保存失敗:", err);
        return false;
    }
}



export async function getJsonDataList(dirHandle) {
    const result = [];
    const entries = [];
    for await (const entry of dirHandle.values()) {
        entries.push(entry);
    }
    const fileEntries = getSortedFileEntries(entries);

    let files = fileEntries.filter((entry) => entry.name.endsWith(".vc_json"));
    for (const entry of files) {
        const file = await entry.getFile();
        const text = await file.text();
        const data = getVCJsonData(text, file.name);
        result.push(data);
    }
    if (result.length) return result;

    files = fileEntries.filter((entry) => entry.name.endsWith(".voice_json"));
    for (const entry of files) {
        const file = await entry.getFile();
        const text = await file.text();
        const data = getVoiceJsonData(file.name, text);
        result.push(data);
    }

    if (result.length) return result;

    const audioEntry = fileEntries.find((entry) => hasExtension(entry.name, AUDIO_EXTENSIONS));
    const imageEntry = fileEntries.find((entry) => hasExtension(entry.name, IMAGE_EXTENSIONS));
    const jsonSubtitleEntries = fileEntries.filter((entry) => entry.name.endsWith(".json"));

    for (const entry of jsonSubtitleEntries) {
        const file = await entry.getFile();
        const text = await file.text();
        const data = getSentenceJsonData(file.name, text, {
            audioFilePath: audioEntry?.name ?? "",
            imageFilePath: imageEntry?.name ?? "",
        });
        if (data) {
            result.push(markAutoGenerated(data, getGeneratedVcJsonName(getBaseName(file.name))));
        }
    }
    if (result.length) return result;

    const srtEntries = fileEntries.filter((entry) => entry.name.endsWith(".srt"));
    if (srtEntries.length || audioEntry || imageEntry) {
        const baseName = getBaseName(audioEntry?.name ?? srtEntries[0]?.name ?? imageEntry?.name ?? dirHandle.name ?? "sample");
        const scriptFiles = srtEntries.length
            ? srtEntries.map((entry) => defaultSrtFileShape({ filePath: entry.name, name: entry.name }))
            : [defaultSrtFileShape({ filePath: getDefaultGeneratedTrackName(baseName), inlineData: [] })];

        result.push(markAutoGenerated(createProjectJsonData({
            name: baseName,
            audioFilePath: audioEntry?.name ?? "",
            imageFilePath: imageEntry?.name ?? "",
            scriptFiles,
        }), getGeneratedVcJsonName(baseName)));
    }
    return result;

}


/*
*　　-- srtdata処理関連 --
*　　字幕ファイル・字幕データ関連の処理
*/
export function getDefaultSrtFiles() {
    return {
        name: "default",
        file_path: '',
        default_class: 'default1',
        height: 50,
        data: [
            {
                id: 1,
                startTimeStr: "00:00:00,000",
                endTimeStr: "00:00:18,330",
                startTime: 0,
                endTime: 18.33,
                text: ''
            }
        ]
    };
}



// SRTファイルをパースしてデータ配列に変換する関数
export function parseSrt(srt_text) {
    if (srt_text === null) return [];

    //srtファイルの構造の記述
    //  "通し番号"
    //  "時間 --> 時間" 
    //  "文章 + 改行2回(もしくは末尾)"
    const blockPattern = /(?:^|\r?\n\r?\n)(\d+)\r?\n([\d:,]+)\s-{2}>\s([\d:,]+)\r?\n([\s\S]*?)(?=\r?\n\r?\n\d+\r?\n|$)/g;

    const srtList = [];
    for (const match of srt_text.matchAll(blockPattern)) {
        srtList.push(parseSrtBlock({
            id: match[1],
            start: match[2],
            end: match[3],
            body: match[4],
        }));
    }
    if (!srtList.length) return [];
    return srtList ? normalizeSrtItems(srtList) : [];
};

/**
 * SRT データの最後のクリップの endTime が duration より短い場合に duration まで引き伸ばす
 * @param {Array} srtData
 * @param {number} duration 秒
 */
export function extendLastClipToDuration(srtData, duration) {
    if (!srtData || srtData.length === 0 || !duration) return;
    const last = srtData[srtData.length - 1];
    if (last.endTime < duration) {
        last.endTime = duration;
        last.endTimeStr = convSecToStr(duration);
    }
}


// SRTファイルのブロックをデータに変換する関数
export function parseSrtBlock(part) {
    let id;
    let start;
    let end;
    let text;
    if (typeof part === "string") {
        const match = part.match(/^(\d+)\r?\n([\d:,]+)\s-{2}>\s([\d:,]+)\r?\n?([\s\S]*)$/);
        if (!match) return null;
        id = parseInt(match[1]);
        start = match[2];
        end = match[3];
        text = match[4] ?? "";
    } else {
        id = parseInt(part.id);
        start = part.start;
        end = part.end;
        text = part.body ?? "";
    }
    const parsedBody = parseSrtBodyText(text);

    const entry = {
        startTimeStr: start,
        endTimeStr: end,
        startTime: convStrToSec(start),
        endTime: convStrToSec(end),
        text: parsedBody.text,
        ...(parsedBody.sentences.length > 1 ? { sentences: parsedBody.sentences } : {}),
        ref: {}
    };
    return entry;
}





export async function saveSrtFile(dirHandle, name, data, subdir = null) {
    if (!dirHandle) return false;

    try {
        // 保存先ディレクトリの取得
        const targetDirHandle = subdir
            ? await dirHandle.getDirectoryHandle(subdir, { create: true })
            : dirHandle;

        // 書き込むファイルのハンドル
        const fileHandle = await targetDirHandle.getFileHandle(name, { create: true });
        const writable = await fileHandle.createWritable();

        // jsondata.name を name に置き換えたコピーを作成
        const nameWithoutExt = name;

        await writable.write(combineToSRT(data));
        await writable.close();

        console.log(`保存完了: ${subdir ? `${subdir}/` : ""}${name}`);
        return true;
    } catch (err) {
        console.error("保存失敗:", err);
        return false;
    }
}

function serializeSentenceJsonSubtitle(data) {
    return JSON.stringify((data ?? []).map((item) => {
        const sentences = Array.isArray(item?.sentences) && item.sentences.length
            ? item.sentences.map((sentence) => normalizeInlineNewlines(sentence).trim()).filter(Boolean)
            : splitTextToSentences(getSrtItemText(item));
        return {
            start: item.startTimeStr ?? convSecToStr(item.startTime ?? 0),
            end: item.endTimeStr ?? convSecToStr(item.endTime ?? 0),
            sentences,
        };
    }), null, 2);
}

async function saveTextFileByPath(dirHandle, path, text, subdir = null) {
    if (!dirHandle) return false;
    try {
        let targetDirHandle = subdir
            ? await dirHandle.getDirectoryHandle(subdir, { create: true })
            : dirHandle;
        const normalizedPath = String(path || "").replace(/\\/g, "/");
        const parts = normalizedPath.split("/").filter(Boolean);
        const fileName = parts.pop();
        if (!fileName) return false;
        for (const part of parts) {
            targetDirHandle = await targetDirHandle.getDirectoryHandle(part, { create: true });
        }
        const fileHandle = await targetDirHandle.getFileHandle(fileName, { create: true });
        const writable = await fileHandle.createWritable();
        await writable.write(text);
        await writable.close();
        console.log(`保存完了: ${subdir ? `${subdir}/` : ""}${normalizedPath}`);
        return true;
    } catch (err) {
        console.error("保存失敗", err);
        return false;
    }
}

export async function saveSubtitleFile(dirHandle, path, data, options = {}) {
    const normalizedPath = String(path || "subtitle.srt").replace(/\\/g, "/");
    if (normalizedPath.toLowerCase().endsWith(".json")) {
        return saveTextFileByPath(dirHandle, normalizedPath, serializeSentenceJsonSubtitle(data));
    }

    const base = normalizedPath.split("/").pop().replace(/\.[^/.]+$/, "") || "subtitle";
    const srtName = `${base}.srt`;
    return saveSrtFile(dirHandle, srtName, data, options.srtSubdir ?? "srt");
}


export function combineToSRT(data) {
    let srtText = "";
    let id = 1;
    for (const srtPart of data) {
        srtText += id + '\r\n';
        srtText += srtPart.startTimeStr + ' --> ' + srtPart.endTimeStr;
        if (getSrtItemText(srtPart)) {
            srtText += '\r\n' + serializeSrtBodyText(srtPart);
            if (srtPart.text !== "\r\n") srtText += '\r\n\r\n';
        } else {
            srtText += '\r\n\u3000\r\n\r\n';
        }
        id++;
    }
    return srtText;
}


export function getCurrentText(data, time) {
    for (let i = 0; i < data.length; i++) {
        const entry = data[i];
        if (time >= entry.startTime && time <= entry.endTime) {
            return { text: getSrtItemText(entry), entry, index: i };
        }
    }
    return { text: "", entry: null, index: -1 }; // 一致なし
}




export const calculate_shadow = ({ enable, steps, offsetX, offsetY, size, color, blur }) => {
    if (!enable) return "none";
    const shadowSize = size;
    const shadowBlur = blur;
    const shadowColor = color;

    let textShadow = "none";
    if (steps == 1) {
        textShadow = `${offsetX}px ${offsetY}px ${shadowBlur}px ${shadowColor}`;
    } else {
        const outerShadows = createShadowDirections(steps).map(
            ([dx, dy]) =>
                `${offsetX + dx * shadowSize}px ${offsetY + dy * shadowSize}px ${shadowBlur}px ${shadowColor}`
        );
        textShadow = [...outerShadows].join(", ");
    }

    return textShadow;
}

const createShadowDirections = (steps, offset = 0) => {
    steps = Math.ceil(steps);
    const angleStep = (2 * Math.PI) / steps;
    return Array.from({ length: steps }, (_, i) => {
        const angle = i * angleStep + offset;
        return [Math.round(Math.cos(angle)), Math.round(Math.sin(angle))];
    });
};



export function convertToStyledSpans(defaultStyleName, text) {
    const result = [];
    const tagPattern = /<(\w+)>([\s\S]*?)<\/>/g;
    let lastIndex = 0;

    for (const match of text.matchAll(tagPattern)) {
        const [fullMatch, styleName, content] = match;
        const start = match.index;

        // タグの前の通常テキスト
        if (start > lastIndex) {
            const normal = text.slice(lastIndex, start);
            result.push({ style: defaultStyleName, text: normal });
        }

        // タグ部分
        result.push({ style: styleName, text: content });

        lastIndex = start + fullMatch.length;
    }

    // 残り
    if (lastIndex < text.length) {
        result.push({ style: defaultStyleName, text: text.slice(lastIndex) });
    }

    return result;
}





function normalizeSrtItems(srtItems) {
    const sorted = [...srtItems].sort((a, b) => a.startTime - b.startTime);
    const normalized = [];

    for (let i = 0; i < sorted.length; i++) {
        const curr = { ...sorted[i] };
        const prev = normalized[normalized.length - 1];

        if (!prev) {
            if (curr.startTime > 0) {
                normalized.push({
                    startTime: 0,
                    endTime: curr.startTime,
                    startTimeStr: "00:00:00,000",
                    endTimeStr: convSecToStr(curr.startTime),
                    text: "　",
                    ref: {}
                });
            }
        } else {
            // 被り解消
            if (curr.startTime < prev.endTime) {
                prev.endTime = curr.startTime;
                prev.endTimeStr = convSecToStr(prev.endTime);
            }

            // 空白時間 → text: "" を挿入
            if (curr.startTime > prev.endTime) {
                normalized.push({
                    startTime: prev.endTime,
                    endTime: curr.startTime,
                    startTimeStr: convSecToStr(prev.endTime),
                    endTimeStr: convSecToStr(curr.startTime),
                    text: "　",
                    ref: {}
                });
            }
        }

        // 時間逆転防止（安全対策）
        if (curr.endTime < curr.startTime) {
            curr.endTime = curr.startTime;
        }

        // str更新
        curr.startTimeStr = convSecToStr(curr.startTime);
        curr.endTimeStr = convSecToStr(curr.endTime);

        // "　" 連続 → 結合処理
        if (
            prev &&
            isOnlyFullWidthSpace(prev.text) &&
            isOnlyFullWidthSpace(curr.text)
        ) {
            // prevのendを伸ばす
            prev.endTime = curr.endTime;
            prev.endTimeStr = convSecToStr(curr.endTime);
        } else {
            normalized.push(curr);
        }
    }

    return normalized;
}

function isOnlyFullWidthSpace(text) {
    return typeof text === "string" && text.trim() === "" && /　/.test(text);
}
