import { expect, test } from "@playwright/test";
import {
  combineToSRT,
  createBlankSubtitleClip,
  createSubtitleFile,
  createSubtitleMediaTrack,
  getAutoGeneratedVcJsonName,
  getJsonDataList,
  getMedia,
  getVCJsonData,
  parseSrt,
  removeCreatedSubtitleFile,
  saveJsonFile,
  saveSubtitleFile,
  saveSubtitleTrack,
  setSrtItemText,
  syncJsonDataFromMedia,
} from "../../src/lib/data_process.js";
import { convSecToStr, convStrToSec } from "../../src/lib/util.js";

function memoryFs(initial = {}, failures = {}) {
  const files = new Map(Object.entries(initial));
  const directories = new Set([""]);
  const writes = [];
  const aborted = [];
  const removed = [];
  for (const path of files.keys()) {
    const parts = path.split("/");
    for (let i = 1; i < parts.length; i++) directories.add(parts.slice(0, i).join("/"));
  }
  const fail = (operation, path) => {
    const name = failures[`${operation}:${path}`];
    if (name) throw new DOMException(operation, name);
  };
  const missing = () => new DOMException("Missing entry", "NotFoundError");
  function directory(prefix = "") {
    const fullPath = (name) => prefix ? `${prefix}/${name}` : name;
    return {
      kind: "directory",
      name: prefix.split("/").pop() || "fixture",
      async removeEntry(name) {
        const path = fullPath(name);
        fail("remove", path);
        if (directories.has(path)) throw new DOMException("Directory not empty", "InvalidModificationError");
        if (!files.has(path)) throw missing();
        files.delete(path);
        removed.push(path);
      },
      async getDirectoryHandle(name, { create = false } = {}) {
        const path = fullPath(name);
        fail("directory", path);
        if (files.has(path)) throw new DOMException("File exists", "TypeMismatchError");
        if (!directories.has(path) && !create) throw missing();
        directories.add(path);
        return directory(path);
      },
      async getFileHandle(name, { create = false } = {}) {
        const path = fullPath(name);
        fail("handle", path);
        if (directories.has(path)) throw new DOMException("Directory exists", "TypeMismatchError");
        if (!files.has(path) && !create) throw missing();
        if (!files.has(path)) files.set(path, "");
        return {
          kind: "file",
          name,
          async getFile() {
            fail("read", path);
            const file = new File([files.get(path)], name);
            file.text = async () => { fail("text", path); return files.get(path); };
            return file;
          },
          async createWritable() {
            fail("writable", path);
            let pending = "";
            return {
              async write(text) { fail("write", path); pending = String(text); },
              async close() {
                fail("close", path);
                files.set(path, pending);
                writes.push(path);
              },
              async abort() { pending = ""; aborted.push(path); },
            };
          },
        };
      },
      async *values() {
        const prefixLength = prefix ? prefix.length + 1 : 0;
        for (const path of files.keys()) {
          if (prefix && !path.startsWith(`${prefix}/`)) continue;
          const name = path.slice(prefixLength);
          if (!name.includes("/")) yield await this.getFileHandle(name);
        }
      },
    };
  }
  return { dir: directory(), files, writes, directory, aborted, removed };
}

function srt(text = "BEFORE") {
  return `1\r\n00:00:00,000 --> 00:00:01,001\r\n${text}\r\n\r\n`;
}

function project(paths, extras = {}) {
  return {
    name: "fixture.vc_json",
    audioFilePath: "",
    scriptFiles: paths.map((filePath) => ({ filePath })),
    ...extras,
  };
}

test("persists exact SRT and JSON references across repeated project reloads", async () => {
  const paths = ["captions.srt", "a/captions.srt", "b/captions.srt", "a/captions.json", "b/captions.json"];
  const initial = Object.fromEntries(paths.map((path) => [path, path.endsWith(".json")
    ? JSON.stringify([{ start: "00:00:00,000", end: "00:00:01,001", sentences: ["BEFORE"] }])
    : srt()]));
  initial["fixture.vc_json"] = JSON.stringify(project(paths));
  const fs = memoryFs(initial);
  const [json] = await getJsonDataList(fs.dir);
  const media = await getMedia(json, fs.dir);
  for (const [i, track] of media.srt_data.entries()) {
    setSrtItemText(track.data[0], `AFTER ${i}\ninline\n\nparagraph`);
    // Deliberately leave cached strings stale: numeric editing must win on disk.
    track.data[0].endTime = 59.9996;
    expect(await saveSubtitleTrack(fs.dir, track)).toBe(true);
  }
  expect(await saveJsonFile(fs.dir, json.name, syncJsonDataFromMedia(json, media))).toBe(true);
  for (let round = 0; round < 3; round++) {
    const [reloadedJson] = await getJsonDataList(fs.dir);
    expect(reloadedJson.scriptFiles.map((item) => item.filePath)).toEqual(paths);
    const reloaded = await getMedia(reloadedJson, fs.dir);
    for (const [i, track] of reloaded.srt_data.entries()) {
      expect(track.loadStatus).toBe("loaded");
      expect(track.data[0].sentences).toEqual([`AFTER ${i}\ninline`, "paragraph"]);
      expect(track.data[0].endTime).toBe(60);
      expect(track.data[0].endTimeStr).toBe("00:01:00,000");
      expect(await saveSubtitleTrack(fs.dir, track)).toBe(true);
    }
  }
  expect([...fs.files.keys()].sort()).toEqual(Object.keys(initial).sort());
});

test("new-track create-only preserves unreferenced JSON and SRT including empty files", async () => {
  const initial = { "other.json": '{"private":"untouched"}', "srt/other.srt": srt("untouched"), "empty.json": "" };
  const fs = memoryFs(initial);
  const data = [createBlankSubtitleClip(2)];
  for (const path of Object.keys(initial)) expect(await createSubtitleFile(fs.dir, path, data)).toBe(false);
  expect(Object.fromEntries(fs.files)).toEqual(initial);
  expect(fs.writes).toEqual([]);
  expect(await createSubtitleFile(fs.dir, "srt/new.srt", data)).toBe(true);
  expect(parseSrt(fs.files.get("srt/new.srt"))[0].endTime).toBe(2);
  expect(await createSubtitleFile(fs.dir, "new.json", data)).toBe(true);
  expect(JSON.parse(fs.files.get("new.json"))[0].end).toBe("00:00:02,000");
});

test("concurrent create calls with distinct handles cannot overwrite the first result", async () => {
  const fs = memoryFs();
  const first = [{ ...createBlankSubtitleClip(1), text: "first" }];
  const second = [{ ...createBlankSubtitleClip(2), text: "second" }];
  const results = await Promise.all([
    createSubtitleFile(fs.dir, "srt/same.srt", first),
    createSubtitleFile(fs.directory(), "srt\\same.srt", second),
  ]);
  expect(results).toEqual([true, false]);
  expect(fs.writes).toEqual(["srt/same.srt"]);
  expect(fs.files.get("srt/same.srt")).toContain("first");
  expect(fs.files.get("srt/same.srt")).not.toContain("second");
});

test("failed reads and parses cannot overwrite sources or create missing references", async () => {
  const initial = {
    "bad.json": "{broken", "shape.json": "{}", "null.json": "null",
    "row.json": '[{"start":"bad","end":"bad","sentences":[]}]',
    "bad.srt": "not a subtitle", "denied.json": "[]", "text.json": "[]",
    "empty.json": "[]", "empty.srt": "",
  };
  const fs = memoryFs(initial, { "read:denied.json": "NotAllowedError", "text:text.json": "NotReadableError" });
  const paths = [...Object.keys(initial), "missing.json", "gone/missing.srt"];
  const media = await getMedia(project(paths, { imageSrtPath: "missing-image.srt" }), fs.dir);
  for (const track of media.srt_data) {
    if (["empty.json", "empty.srt"].includes(track.file_path)) {
      expect(track.loadStatus).toBe("loaded");
      expect(track.loadError).toBeNull();
      expect(track.data).toEqual([]);
    } else {
      expect(track.loadStatus).toBe("error");
      expect(track.loadError).toBeTruthy();
      expect(await saveSubtitleTrack(fs.dir, track)).toBe(false);
      expect(await saveSubtitleFile(fs.dir, track.file_path, [], { loadStatus: track.loadStatus })).toBe(false);
    }
  }
  expect(Object.fromEntries(fs.files)).toEqual(initial);
  expect(fs.writes).toEqual([]);
});

test("late candidate load failures release audio resources before rethrowing", async () => {
  const fs = memoryFs({ "sample.mp3": "fixture" });
  const OriginalAudio = globalThis.Audio;
  const originalCreate = URL.createObjectURL;
  const originalRevoke = URL.revokeObjectURL;
  const created = [];
  const revoked = [];
  const audioInstances = [];
  globalThis.Audio = class {
    constructor(src) {
      this.src = src;
      this.duration = 1;
      audioInstances.push(this);
      setTimeout(() => this.onloadedmetadata(), 0);
    }
    pause() { this.paused = true; }
    removeAttribute(name) { if (name === "src") this.src = null; }
    load() { this.released = true; }
  };
  URL.createObjectURL = (file) => { const url = originalCreate(file); created.push(url); return url; };
  URL.revokeObjectURL = (url) => { revoked.push(url); originalRevoke(url); };
  try {
    for (const extras of [{ imageFilePath: 123 }, { scriptFiles: [{ filePath: "", inlineData: [null] }] }]) {
      await expect(getMedia(project([], { audioFilePath: "sample.mp3", ...extras }), fs.dir)).rejects.toThrow();
    }
    expect(revoked).toEqual(created);
    expect(created).toHaveLength(2);
    expect(audioInstances.every((audio) => audio.paused && audio.released && audio.src === null)).toBe(true);
  } finally {
    if (OriginalAudio === undefined) delete globalThis.Audio;
    else globalThis.Audio = OriginalAudio;
    URL.createObjectURL = originalCreate;
    URL.revokeObjectURL = originalRevoke;
  }
});

test("synthetic inline empty tracks are loaded but missing uninitialized tracks are not", async () => {
  const fs = memoryFs();
  const json = project([], { scriptFiles: [{ filePath: "srt/new.srt", inlineData: [] }, { filePath: "" }] });
  const media = await getMedia(json, fs.dir);
  expect(media.srt_data.map((track) => track.loadStatus)).toEqual(["loaded", "unloaded"]);
  expect(await saveSubtitleTrack(fs.dir, media.srt_data[0])).toBe(true);
  expect(await saveSubtitleTrack(fs.dir, media.srt_data[1])).toBe(false);
  expect(fs.files.get("srt/new.srt")).toBe("");
  const defaults = getVCJsonData(JSON.stringify(project([])));
  expect(defaults.scriptFiles[0].filePath).toBe("srt/fixture.srt");
  expect(defaults.scriptFiles[0].inlineData).toEqual([]);
  const created = createSubtitleMediaTrack({ id: 0, name: "new", filePath: "srt/new.srt", data: [] });
  expect(created.loadStatus).toBe("loaded");
  expect(await saveSubtitleTrack(fs.dir, { ...created, loadStatus: undefined })).toBe(false);
});

test("materialized synthetic blank projects remain valid after vc_json serialization and reload", async () => {
  const fs = memoryFs({ "cover.png": "fixture" });
  const [generated] = await getJsonDataList(fs.dir);
  const name = getAutoGeneratedVcJsonName(generated);
  expect(name).toBe("cover.vc_json");
  expect(generated.scriptFiles[0].filePath).toBe("srt/cover.srt");
  expect(generated.scriptFiles[0].inlineData).toEqual([]);
  for (const script of generated.scriptFiles) {
    expect(await createSubtitleFile(fs.dir, script.filePath, script.inlineData)).toBe(true);
  }
  expect(await saveJsonFile(fs.dir, name, generated)).toBe(true);
  expect(JSON.parse(fs.files.get(name)).scriptFiles[0].inlineData).toBeUndefined();
  const [saved] = await getJsonDataList(fs.dir);
  const media = await getMedia(saved, fs.dir);
  expect(media.srt_data[0].loadStatus).toBe("loaded");
  expect(media.srt_data[0].data).toEqual([]);
  media.srt_data[0].data.push({ ...createBlankSubtitleClip(1.001), text: "first edit" });
  expect(await saveSubtitleTrack(fs.dir, media.srt_data[0])).toBe(true);
  const reloaded = await getMedia((await getJsonDataList(fs.dir))[0], fs.dir);
  expect(reloaded.srt_data[0].loadStatus).toBe("loaded");
  expect(reloaded.srt_data[0].data[0].text).toBe("first edit");
  expect(reloaded.srt_data[0].data[0].endTimeStr).toBe("00:00:01,001");
  URL.revokeObjectURL(media.image_data.currentImage);
  URL.revokeObjectURL(reloaded.image_data.currentImage);
});

test("empty inline baselines cannot mask existing file contents or read failures", async () => {
  const fs = memoryFs({ "existing.srt": srt("existing"), "bad.json": "{broken", "denied.json": "[]" }, {
    "read:denied.json": "NotAllowedError",
  });
  const json = project([], { scriptFiles: ["existing.srt", "bad.json", "denied.json"].map((filePath) => ({ filePath, inlineData: [] })) });
  const media = await getMedia(json, fs.dir);
  expect(media.srt_data.map((track) => track.loadStatus)).toEqual(["loaded", "error", "error"]);
  expect(media.srt_data[0].data[0].text).toBe("existing");
  for (const track of media.srt_data.slice(1)) expect(await saveSubtitleTrack(fs.dir, track)).toBe(false);
  expect(fs.writes).toEqual([]);
});

test("referenced subtitles outrank stale inlineData and survive save plus project reload", async () => {
  const data = project([], { scriptFiles: [{ filePath: "edited.srt", inlineData: parseSrt(srt("stale inline")) }] });
  const fs = memoryFs({ "fixture.vc_json": JSON.stringify(data), "edited.srt": srt("saved file") });
  const loaded = await getMedia((await getJsonDataList(fs.dir))[0], fs.dir);
  expect(loaded.srt_data[0].data[0].text).toBe("saved file");
  setSrtItemText(loaded.srt_data[0].data[0], "next edit");
  expect(await saveSubtitleTrack(fs.dir, loaded.srt_data[0])).toBe(true);
  const reloaded = await getMedia((await getJsonDataList(fs.dir))[0], fs.dir);
  expect(reloaded.srt_data[0].data[0].text).toBe("next edit");
  expect(JSON.parse(fs.files.get("fixture.vc_json")).scriptFiles[0].inlineData[0].text).toBe("stale inline");
});

test("inline recovery is used only for absent references, never parse or permission failures", async () => {
  const paths = ["missing.srt", "", "broken.json", "denied.srt"];
  const fs = memoryFs({ "broken.json": "{broken", "denied.srt": srt() }, { "read:denied.srt": "NotAllowedError" });
  const data = project([], { scriptFiles: paths.map((filePath) => ({ filePath, inlineData: parseSrt(srt("recovery")) })) });
  const loaded = await getMedia(data, fs.dir);
  expect(loaded.srt_data.map((track) => track.loadStatus)).toEqual(["loaded", "loaded", "error", "error"]);
  expect(loaded.srt_data.slice(0, 2).every((track) => track.data[0].text === "recovery")).toBe(true);
  for (const track of loaded.srt_data.slice(2)) expect(await saveSubtitleTrack(fs.dir, track)).toBe(false);
  expect(fs.writes).toEqual([]);
});

test("image boundary edits persist in their referenced SRT without losing image paths", async () => {
  const imageSrt = `${srt("images/first.png")}2\r\n00:00:01,001 --> 00:00:03,003\r\nimages/second.png\r\n\r\n`;
  const fs = memoryFs({ "images/timing.srt": imageSrt, "images/first.png": "fixture" });
  const json = project([], { imageSrtPath: "images/timing.srt" });
  const media = await getMedia(json, fs.dir);
  const image = media.srt_data[0];
  expect(image.isImageTrack).toBe(true);
  image.data[0].endTime = 1.999;
  image.data[1].startTime = 1.999;
  expect(await saveSubtitleTrack(fs.dir, image)).toBe(true);
  expect(await saveJsonFile(fs.dir, json.name, syncJsonDataFromMedia(json, media))).toBe(true);
  const [saved] = await getJsonDataList(fs.dir);
  const reloaded = await getMedia(saved, fs.dir);
  const track = reloaded.srt_data.find((item) => item.isImageTrack);
  expect(track.file_path).toBe("images/timing.srt");
  expect(track.data.map(({ startTime, endTime, text }) => ({ startTime, endTime, text }))).toEqual([
    { startTime: 0, endTime: 1.999, text: "images/first.png" },
    { startTime: 1.999, endTime: 3.003, text: "images/second.png" },
  ]);
  URL.revokeObjectURL(media.image_data.currentImage);
  URL.revokeObjectURL(reloaded.image_data.currentImage);
});

test("folder discovery skips unrelated JSON without treating it as empty subtitles", async () => {
  const fs = memoryFs({ "settings.json": '{"setting":true}', "captions.srt": srt() });
  const list = await getJsonDataList(fs.dir);
  expect(list).toHaveLength(1);
  expect(list[0].scriptFiles[0].filePath).toBe("captions.srt");
});

test("creation stops on permission errors, directories, and invalid paths", async () => {
  const fs = memoryFs({ "collision/child.json": "[]" }, { "handle:denied.json": "NotAllowedError" });
  for (const path of ["denied.json", "collision", "../escape.srt", "/absolute.srt", "C:\\absolute.srt", ""]) {
    expect(await createSubtitleFile(fs.dir, path, [])).toBe(false);
  }
  expect(fs.writes).toEqual([]);
  expect(Object.fromEntries(fs.files)).toEqual({ "collision/child.json": "[]" });
});

test("write failures preserve committed content and report failure", async () => {
  const fs = memoryFs({ "captions.srt": srt() }, { "close:captions.srt": "NotAllowedError" });
  expect(await saveSubtitleFile(fs.dir, "captions.srt", [{ ...createBlankSubtitleClip(), text: "AFTER" }])).toBe(false);
  expect(fs.files.get("captions.srt")).toBe(srt());
  expect(fs.writes).toEqual([]);
});

test("failed creation does not stall later creates or report false success", async () => {
  const failures = { "write:srt/failed.srt": "NotAllowedError" };
  const fs = memoryFs({}, failures);
  expect(await createSubtitleFile(fs.dir, "srt/failed.srt", [createBlankSubtitleClip()])).toBe(false);
  expect(fs.files.has("srt/failed.srt")).toBe(false);
  expect(fs.aborted).toEqual(["srt/failed.srt"]);
  delete failures["write:srt/failed.srt"];
  expect(await createSubtitleFile(fs.dir, "srt/failed.srt", [createBlankSubtitleClip()])).toBe(true);
  expect(await createSubtitleFile(fs.dir, "srt/next.srt", [createBlankSubtitleClip()])).toBe(true);
  expect(fs.writes).toEqual(["srt/failed.srt", "srt/next.srt"]);
});

test("failed new project save aborts and allows synthetic materialization retry", async () => {
  const failures = { "close:cover.vc_json": "NotAllowedError" };
  const fs = memoryFs({ "cover.png": "fixture" }, failures);
  const [generated] = await getJsonDataList(fs.dir);
  const path = generated.scriptFiles[0].filePath;
  expect(await createSubtitleFile(fs.dir, path, [])).toBe(true);
  expect(await saveJsonFile(fs.dir, "cover.vc_json", generated)).toBe(false);
  expect(fs.aborted).toEqual(["cover.vc_json"]);
  expect(fs.files.has("cover.vc_json")).toBe(false);
  expect(await removeCreatedSubtitleFile(fs.dir, path)).toBe(true);
  expect(fs.files.has(path)).toBe(false);
  delete failures["close:cover.vc_json"];
  const [retry] = await getJsonDataList(fs.dir);
  expect(await createSubtitleFile(fs.dir, retry.scriptFiles[0].filePath, [])).toBe(true);
  expect(await saveJsonFile(fs.dir, "cover.vc_json", retry)).toBe(true);
  expect((await getJsonDataList(fs.dir))[0].scriptFiles[0].filePath).toBe(path);
});

test("failed existing project save never removes or alters the original", async () => {
  const original = JSON.stringify(project(["a.srt"]));
  const fs = memoryFs({ "fixture.vc_json": original }, { "write:fixture.vc_json": "NotAllowedError" });
  expect(await saveJsonFile(fs.dir, "fixture.vc_json", project(["b.srt"]))).toBe(false);
  expect(fs.files.get("fixture.vc_json")).toBe(original);
  expect(fs.aborted).toEqual(["fixture.vc_json"]);
  expect(fs.removed).toEqual([]);
});

test("JSON save snapshots nested project state before any asynchronous file access", async () => {
  const fs = memoryFs();
  const data = project(["before.srt"]);
  const saving = saveJsonFile(fs.dir, "fixture.vc_json", data);
  data.scriptFiles[0].filePath = "after.srt";
  expect(await saving).toBe(true);
  expect(JSON.parse(fs.files.get("fixture.vc_json")).scriptFiles[0].filePath).toBe("before.srt");
});

test("known-created rollback rejects directory and traversal paths without recursive removal", async () => {
  const fs = memoryFs({ "srt/retained.srt": srt() });
  expect(await removeCreatedSubtitleFile(fs.dir, "srt")).toBe(false);
  expect(await removeCreatedSubtitleFile(fs.dir, "../srt/retained.srt")).toBe(false);
  expect(fs.files.get("srt/retained.srt")).toBe(srt());
  expect(fs.removed).toEqual([]);
});

test("millisecond conversion and repeated SRT roundtrips preserve boundary values", () => {
  for (const milliseconds of [0, 1, 999, 1001, 1007, 59999, 60001, 3599999, 3600001, 86400001]) {
    let seconds = milliseconds / 1000;
    for (let i = 0; i < 10; i++) {
      const text = convSecToStr(seconds);
      seconds = convStrToSec(text);
      expect(Math.round(seconds * 1000)).toBe(milliseconds);
      const parsed = parseSrt(combineToSRT([{ ...createBlankSubtitleClip(), endTime: seconds, text: "roundtrip" }]));
      expect(parsed[0].endTimeStr).toBe(text);
    }
  }
  expect(convSecToStr(59.9996)).toBe("00:01:00,000");
  expect(convSecToStr(3599.9996)).toBe("01:00:00,000");
});
