import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import {
  combineToSRT,
  getAutoGeneratedVcJsonName,
  getVCJsonData,
  getJsonDataList,
  parseSrt,
  saveSubtitleFile,
  setSrtItemText,
  syncJsonDataFromMedia,
} from "../../src/lib/data_process.js";

const sentenceJson = JSON.stringify([
  {
    speaker: "",
    start: "00:00:00,000",
    end: "00:00:02,000",
    sentences: ["こんにちは。", "イエカノでーす。"],
  },
  {
    speaker: "",
    start: "00:00:02,000",
    end: "00:00:04,000",
    sentences: ["あ゛あ゜ア゛ア゜"],
  },
]);

test("uses full-width-space SRT lines for sentence breaks and normal lines for inline breaks", () => {
  const srtText = "1\r\n00:00:00,000 --> 00:00:02,000\r\n段落1の1行目\r\n段落1の2行目\r\n \t \r\n段落2\r\n　\r\n段落3\r\n\r\n";
  const parsed = parseSrt(srtText);

  expect(parsed).toHaveLength(1);
  expect(parsed[0].sentences).toEqual(["段落1の1行目\n段落1の2行目", "段落2", "段落3"]);
  expect(combineToSRT(parsed)).toContain("段落1の1行目\r\n段落1の2行目\r\n　\r\n段落2\r\n　\r\n段落3");
});

test("uses blank editor lines as sentence breaks for json save", () => {
  const item = { startTime: 0, endTime: 1, startTimeStr: "00:00:00,000", endTimeStr: "00:00:01,000", text: "" };
  setSrtItemText(item, "段落1\n\n段落2\n　\n段落3の1行目\n段落3の2行目");
  expect(item.sentences).toEqual(["段落1", "段落2", "段落3の1行目\n段落3の2行目"]);
  expect(combineToSRT([item])).toContain("段落1\r\n　\r\n段落2\r\n　\r\n段落3の1行目\r\n段落3の2行目");

  const synced = syncJsonDataFromMedia(
    { name: "sample.vc_json", scriptFiles: [{ filePath: "sample.srt" }] },
    { srt_data: [{ id: 0, data: [item] }] },
  );
  expect(synced.scriptFiles[0].inlineData).toBeUndefined();
});

test("keeps existing vc_json as the canonical project source", async () => {
  const vcJsonText = JSON.stringify({
    name: "canonical.vc_json",
    audioFilePath: "canonical.mp3",
    srtFiles: [{
      filePath: "canonical.srt",
      name: "canonical.srt",
      inlineData: [{
        startTimeStr: "00:00:00,000",
        endTimeStr: "00:00:01,000",
        startTime: 0,
        endTime: 1,
        text: "vc_jsonの字幕",
        sentences: ["vc_jsonの字幕"],
      }],
    }],
  });
  const sidecarJsonText = JSON.stringify([{
    start: "00:00:00,000",
    end: "00:00:01,000",
    sentences: ["横のjson字幕"],
  }]);

  const makeEntry = (name, text) => ({
    kind: "file",
    name,
    async getFile() {
      return new File([text], name);
    },
  });
  const dirHandle = {
    async *values() {
      yield makeEntry("canonical.vc_json", vcJsonText);
      yield makeEntry("sidecar.json", sidecarJsonText);
      yield makeEntry("sidecar.srt", "1\r\n00:00:00,000 --> 00:00:01,000\r\n横のsrt字幕\r\n");
    },
  };

  const list = await getJsonDataList(dirHandle);
  expect(list).toHaveLength(1);
  expect(getAutoGeneratedVcJsonName(list[0])).toBeNull();
  expect(list[0].scriptFiles[0].filePath).toBe("canonical.srt");
  expect(list[0].scriptFiles[0].inlineData[0].sentences).toEqual(["vc_jsonの字幕"]);
  expect(list[0].srtFiles).toBeUndefined();
});

test("normalizes jsonFiles to scriptFiles when reading vc_json", () => {
  const data = getVCJsonData(JSON.stringify({
    name: "json-files.vc_json",
    jsonFiles: [{ filePath: "sample.json", name: "sample.json" }],
  }), "json-files.vc_json");

  expect(data.scriptFiles[0].filePath).toBe("sample.json");
  expect(data.srtFiles).toBeUndefined();
  expect(data.jsonFiles).toBeUndefined();
});

test("saves json subtitle tracks as json sentences instead of SRT", async () => {
  const writes = {};
  const dirHandle = {
    async getFileHandle(name, options = {}) {
      if (!options.create) throw new DOMException(`Missing file: ${name}`, "NotFoundError");
      return {
        async createWritable() {
          const chunks = [];
          return {
            async write(chunk) {
              chunks.push(String(chunk));
            },
            async close() {
              writes[name] = chunks.join("");
            },
          };
        },
      };
    },
  };

  const ok = await saveSubtitleFile(dirHandle, "sample.json", [{
    startTimeStr: "00:00:00,000",
    endTimeStr: "00:00:02,000",
    startTime: 0,
    endTime: 2,
    sentences: ["段落1", "段落2の1行目\n段落2の2行目"],
    text: "段落1\r\n段落2の1行目\n段落2の2行目",
  }]);

  expect(ok).toBe(true);
  expect(writes["sample.json"]).toBeTruthy();
  expect(writes["sample.srt"]).toBeUndefined();
  expect(JSON.parse(writes["sample.json"])).toEqual([{
    start: "00:00:00,000",
    end: "00:00:02,000",
    sentences: ["段落1", "段落2の1行目\n段落2の2行目"],
  }]);
});

test("saves SRT subtitle tracks under the srt folder", async () => {
  const writes = {};
  const srtDirHandle = {
    async getFileHandle(name, options = {}) {
      if (!options.create) throw new DOMException(`Missing file: ${name}`, "NotFoundError");
      return {
        async createWritable() {
          const chunks = [];
          return {
            async write(chunk) {
              chunks.push(String(chunk));
            },
            async close() {
              writes[`srt/${name}`] = chunks.join("");
            },
          };
        },
      };
    },
  };
  const dirHandle = {
    async getDirectoryHandle(name, options = {}) {
      if (name === "srt" && options.create) return srtDirHandle;
      throw new DOMException(`Missing directory: ${name}`, "NotFoundError");
    },
  };

  const ok = await saveSubtitleFile(dirHandle, "sample.srt", [{
    startTimeStr: "00:00:00,000",
    endTimeStr: "00:00:02,000",
    startTime: 0,
    endTime: 2,
    text: "字幕",
  }]);

  expect(ok).toBe(true);
  expect(writes["srt/sample.srt"]).toContain("字幕");
});

async function editorInnerText(page, index = 0) {
  return page.locator(".editor").nth(index).evaluate((element) => element.innerText.replace(/\u200B/g, "").replace(/\n$/, ""));
}

async function selectEditorText(page, index, text) {
  await page.locator(".editor").nth(index).evaluate((element, targetText) => {
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      const start = node.textContent.indexOf(targetText);
      if (start >= 0) {
        const range = document.createRange();
        range.setStart(node, start);
        range.setEnd(node, start + targetText.length);
        const selection = window.getSelection();
        selection.removeAllRanges();
        selection.addRange(range);
        return;
      }
    }
    throw new Error(`Text not found: ${targetText}`);
  }, text);
}

async function placeCaretAtEditorEnd(page, index = 0) {
  await page.locator(".editor").nth(index).evaluate((element) => {
    const range = document.createRange();
    range.selectNodeContents(element);
    range.collapse(false);
    const selection = window.getSelection();
    selection.removeAllRanges();
    selection.addRange(range);
    element.focus();
  });
}

async function openEditorContextMenu(page, index = 0) {
  const box = await page.locator(".editor").nth(index).boundingBox();
  if (!box) throw new Error("editor is not visible");
  const viewport = page.viewportSize() ?? { width: 1280, height: 720 };
  await page.locator(".editor").nth(index).dispatchEvent("contextmenu", {
    bubbles: true,
    cancelable: true,
    clientX: Math.min(box.x + 20, viewport.width - 20),
    clientY: Math.min(box.y + 20, viewport.height - 20),
  });
}

test("does not create page-level vertical scrolling in the empty project view", async ({ page }) => {
  await page.goto("/");
  await expect.poll(() => page.evaluate(() => {
    const root = document.scrollingElement || document.documentElement;
    return {
      rootOverflow: root.scrollHeight - root.clientHeight,
      bodyOverflow: document.body.scrollHeight - document.body.clientHeight,
      mainOverflowMode: getComputedStyle(document.querySelector("main")).overflow,
    };
  })).toEqual({
    rootOverflow: 0,
    bodyOverflow: 0,
    mainOverflowMode: "hidden",
  });
});

test("loads a sentences json folder with the rich editor state intact", async ({ page }) => {
  const consoleErrors = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });

  await page.setViewportSize({ width: 2000, height: 1400 });

  await page.addInitScript((jsonText) => {
    const writes = {};
    window.__writes = writes;

    const makeFileEntry = (name, text, type = "application/json") => ({
      kind: "file",
      name,
      async getFile() {
        return new File([text], name, { type });
      },
    });

    const jsonEntry = makeFileEntry("sample.json", jsonText);
    const handles = {
      "sample.json": jsonEntry,
      "sample.mp3": {
        async getFile() {
          return new File([new Uint8Array([0])], "sample.mp3", { type: "audio/mpeg" });
        },
      },
    };

    window.showDirectoryPicker = async () => ({
      name: "mock-sentences-folder",
      async requestPermission() {
        return "granted";
      },
      async *values() {
        yield jsonEntry;
      },
      async getFileHandle(name, options = {}) {
        if (options.create) {
          return {
            async createWritable() {
              const chunks = [];
              return {
                async write(chunk) {
                  chunks.push(String(chunk));
                },
                async close() {
                  writes[name] = chunks.join("");
                },
              };
            },
          };
        }
        if (handles[name]) return handles[name];
        throw new DOMException(`Missing file: ${name}`, "NotFoundError");
      },
    });
  }, sentenceJson);

  await page.goto("/");

  await page.locator("button").first().click();
  await expect(page.locator(".folder-path").first()).toContainText("mock-sentences-folder");
  await expect.poll(() => page.evaluate(() => Object.keys(window.__writes))).toContain("sample.vc_json");
  const generatedFromJsonOnly = await page.evaluate(() => JSON.parse(window.__writes["sample.vc_json"]));
  expect(generatedFromJsonOnly.scriptFiles[0].filePath).toBe("sample.json");
  expect(generatedFromJsonOnly.scriptFiles[0].name).toBe("sample.json");
  await page.locator("[data-testid='new-subtitle-track-name']").fill("追加字幕");
  await page.locator("[data-testid='new-subtitle-track-format']").selectOption("json");
  await page.locator("[data-testid='create-subtitle-track']").click();
  await expect.poll(() => page.evaluate(() => Object.keys(window.__writes))).toContain("追加字幕.json");
  await expect(page.locator(".srt_select").first()).toContainText("追加字幕.json");
  const updatedVcJson = await page.evaluate(() => JSON.parse(window.__writes["sample.vc_json"]));
  expect(updatedVcJson.scriptFiles.map((item) => item.filePath)).toContain("追加字幕.json");
  expect(JSON.parse(await page.evaluate(() => window.__writes["追加字幕.json"]))).toEqual([{
    start: "00:00:00,000",
    end: "00:00:04,000",
    sentences: [],
  }]);
  await page.locator(".srt_select").first().selectOption("0");
  const autoScroll = page.locator("#AutoScrollButton");
  const autoScrollBeforeBold = await autoScroll.isChecked();
  await page.locator("label[for='StyleBoldButton']").click();
  expect(await autoScroll.isChecked()).toBe(autoScrollBeforeBold);
  await expect(page.locator(".sentenceTextArea")).toHaveCount(0);
  await expect(page.locator(".editor")).toHaveCount(2);
  await expect.poll(() => editorInnerText(page, 0)).toBe("こんにちは。\n\nイエカノでーす。");
  const emptyEditor = page.locator(".editor").nth(0);
  await emptyEditor.fill("A");
  await expect.poll(() => editorInnerText(page, 0)).toBe("A");
  await placeCaretAtEditorEnd(page, 0);
  await page.keyboard.press("Enter");
  await page.keyboard.type("B");
  await expect.poll(() => editorInnerText(page, 0)).toBe("A\nB");
  await page.keyboard.press("Shift+Enter");
  await page.keyboard.type("C");
  await expect.poll(() => editorInnerText(page, 0)).toBe("A\nB\nC");
  await emptyEditor.fill("こんにちは。\n\nイエカノでーす。");
  await expect(page.locator(".resize-handle")).toHaveCount(16);
  await expect(page.locator(".resize-handle").first()).not.toBeVisible();

  const box = page.locator(".srt_box").first();
  const text = box;
  const renderedText = page.locator(".srt_text").first();
  await text.click();
  await expect(page.locator(".resize-handle").first()).toBeVisible();
  await page.locator("label[for='StyleBoldButton']").click();
  await expect(page.locator(".resize-handle").first()).toBeVisible();
  await page.locator("input[type='number']").first().click();
  await expect(page.locator(".resize-handle").first()).toBeVisible();
  await page.locator(".editor").first().click();
  await expect(page.locator(".resize-handle").first()).not.toBeVisible();
  await text.click();
  await expect(page.locator(".resize-handle").first()).toBeVisible();

  await page.getByTitle("字幕枠の編集ハンドル表示").locator("input").check({ force: true });
  await expect(page.locator(".resize-handle").first()).toBeVisible();

  const shadowStyle = await renderedText.evaluate((element) => ({
    shadowText: getComputedStyle(element.querySelector(".srt_shadow")).textShadow,
    contentStroke: getComputedStyle(element.querySelector(".srt_content")).webkitTextStrokeWidth,
    beforeDisplay: getComputedStyle(element, "::before").display,
    afterDisplay: getComputedStyle(element, "::after").display,
  }));
  expect(shadowStyle.shadowText).not.toBe("none");
  expect(shadowStyle.contentStroke).not.toBe("0px");
  expect(shadowStyle.beforeDisplay).toBe("none");
  expect(shadowStyle.afterDisplay).toBe("none");
  await expect(page.locator(".srt_sentence.sentence_gap")).toHaveCount(1);
  await expect(page.locator(".srt_sentence.sentence_gap").first()).toHaveCSS("margin-block-start", "26px");

  await page.locator(".bar-container input[type='range']").fill("2.1");
  await expect(page.locator(".srt_text").first()).toHaveAttribute("data-text", "あ\u3099あ\u309Aア\u3099ア\u309A");
  expect(consoleErrors).toEqual([]);
});

test("keeps the original editor context menu operations", async ({ page }) => {
  await page.addInitScript((jsonText) => {
    const writes = {};
    window.__writes = writes;
    const jsonEntry = {
      kind: "file",
      name: "sample.json",
      async getFile() {
        return new File([jsonText], "sample.json", { type: "application/json" });
      },
    };
    window.showDirectoryPicker = async () => ({
      name: "mock-context-menu-folder",
      async requestPermission() {
        return "granted";
      },
      async *values() {
        yield jsonEntry;
      },
      async getFileHandle(name, options = {}) {
        if (options.create && name.endsWith(".vc_json")) {
          return {
            async createWritable() {
              return { async write() {}, async close() {} };
            },
          };
        }
        if (name === "sample.json") return jsonEntry;
        throw new DOMException(`Missing file: ${name}`, "NotFoundError");
      },
    });
  }, sentenceJson);

  await page.goto("/");
  await page.locator("button").first().click();
  await expect(page.locator(".editor")).toHaveCount(2);

  await selectEditorText(page, 0, "こんにちは");
  await openEditorContextMenu(page, 0);
  await page.getByText("タグを付ける").hover();
  await page.locator(".submenu-panel .menu-item").filter({ hasText: "default-style-1" }).click();
  await expect(page.locator(".editor span[data-tag='default-style-1']")).toHaveCount(1);

  await page.locator(".editor span[data-tag='default-style-1']").dispatchEvent("contextmenu", {
    bubbles: true,
    cancelable: true,
    clientX: 120,
    clientY: 120,
  });
  await page.getByText("タグを外す").click();
  await expect(page.locator(".editor span[data-tag='default-style-1']")).toHaveCount(0);

  await openEditorContextMenu(page, 0);
  await page.getByText("下と結合する").click();
  await expect(page.locator(".editor")).toHaveCount(1);
  await expect.poll(() => editorInnerText(page, 0)).toBe("こんにちは。\n\nイエカノでーす。\n\nあ゛あ゜ア゛ア゜");
});

test("keeps inline style tags inside sentence arrays and edits the selected style only", async ({ page }) => {
  const writes = {};
  const vcJsonName = "styled.vc_json";
  const vcJsonText = JSON.stringify({
    name: vcJsonName,
    audioFilePath: "",
    imageFilePath: "",
    styles: {
      "default-style-1": {
        font: "りいポップ角",
        fontSize: 40,
        textColor: "#ffffff",
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpace: 0,
        lineSpace: 10,
        outline1: { enable: true, size: 5, color: "#000000" },
        outline2: { enable: false, size: 0, color: "#000000", offsetX: 0, offsetY: 0 },
        shadow: { enable: true, color: "#000000", offsetX: 0, offsetY: 0, blur: 6, size: 2, steps: 8 },
      },
      accent: {
        font: "りいポップ角",
        fontSize: 44,
        textColor: "#ffcc00",
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpace: 0,
        lineSpace: 10,
        outline1: { enable: true, size: 5, color: "#000000" },
        outline2: { enable: false, size: 0, color: "#000000", offsetX: 0, offsetY: 0 },
        shadow: { enable: true, color: "#000000", offsetX: 0, offsetY: 0, blur: 6, size: 2, steps: 8 },
      },
    },
    scriptFiles: [{
      filePath: "styled.json",
      name: "styled.json",
      defaultStyle: "default-style-1",
      x: 100,
      y: 100,
      maxWidth: 800,
      maxHeight: 300,
      boxAlignX: 50,
      boxAlignY: 50,
      textRotate: "horizontal-tb",
      textAlign: "center",
      inlineData: [{
        startTimeStr: "00:00:00,000",
        endTimeStr: "00:00:03,000",
        startTime: 0,
        endTime: 3,
        text: "通常 <accent>強調\r\n継続\r\n終了</> 通常 <missing>未定義</>",
        sentences: ["通常 <accent>強調", "継続", "終了</> 通常 <missing>未定義</>"],
      }],
    }],
  });

  await page.addInitScript(({ vcJsonName, vcJsonText }) => {
    const writes = {};
    window.__writes = writes;
    const files = {
      [vcJsonName]: { text: vcJsonText, type: "application/json" },
    };
    const makeEntry = (name) => ({
      kind: "file",
      name,
      async getFile() {
        const file = files[name];
        return new File([file.text], name, { type: file.type });
      },
    });
    window.showDirectoryPicker = async () => ({
      name: "styled-folder",
      async requestPermission() {
        return "granted";
      },
      async *values() {
        yield makeEntry(vcJsonName);
      },
      async getFileHandle(name, options = {}) {
        if (options.create && name === vcJsonName) {
          return {
            async createWritable() {
              const chunks = [];
              return {
                async write(chunk) {
                  chunks.push(String(chunk));
                },
                async close() {
                  writes[name] = chunks.join("");
                },
              };
            },
          };
        }
        if (!files[name]) throw new DOMException(`Missing file: ${name}`, "NotFoundError");
        return makeEntry(name);
      },
    });
  }, { vcJsonName, vcJsonText });

  await page.goto("/");
  await page.locator("button").first().click();

  await expect(page.locator(".folder-path").first()).toContainText("styled-folder");
  await expect(page.locator(".srt_sentence")).toHaveCount(3);
  await expect(page.locator(".srt_sentence.sentence_gap")).toHaveCount(2);
  await expect(page.locator(".srt_text[data-tag='accent']")).toHaveCount(3);
  await expect(page.locator(".srt_text[data-tag='missing']")).toHaveCount(0);
  await expect.poll(() => editorInnerText(page, 0)).toBe("通常 強調\n\n継続\n\n終了 通常 未定義");

  const accentText = page.locator(".srt_text[data-tag='accent']").first();
  const defaultText = page.locator(".srt_text[data-tag='default-style-1']").first();
  await expect(page.locator(".srt_sentence").nth(1).locator(".srt_text[data-tag='accent']")).toHaveAttribute("data-text", "継続");
  await expect(page.locator(".srt_sentence").nth(2).locator(".srt_text[data-tag='default-style-1'][data-text=' 通常 ']")).toHaveCount(1);
  await page.locator("[data-testid='new-style-key']").fill("missing");
  await page.locator("[data-testid='add-style-key']").click();
  await expect(page.locator(".srt_text[data-tag='missing']")).toHaveCount(1);
  await page.locator(".srt_text[data-tag='missing']").click();
  await page.locator("label[for='StyleBoldButton']").click();
  await expect(page.locator(".srt_text[data-tag='missing'] .srt_content")).toHaveCSS("font-weight", "700");
  await accentText.click();
  await page.locator("label[for='StyleBoldButton']").click();

  await expect(accentText.locator(".srt_content")).toHaveCSS("font-weight", "700");
  await expect(defaultText.locator(".srt_content")).not.toHaveCSS("font-weight", "700");

  await page.locator("button[title='vc_jsonを保存']").click();
  await expect.poll(() => page.evaluate((name) => window.__writes[name], vcJsonName)).toBeTruthy();
  const saved = await page.evaluate((name) => JSON.parse(window.__writes[name]), vcJsonName);
  expect(saved.styles.accent.fontWeight).toBe("bold");
  expect(saved.styles.missing.fontWeight).toBe("bold");
  expect(saved.styles["default-style-1"].fontWeight).toBe("normal");
  expect(saved.scriptFiles[0].inlineData).toBeUndefined();
  expect(saved.srtFiles).toBeUndefined();
  expect(saved.jsonFiles).toBeUndefined();
});

test("generates vc_json from the いえカノ folder and prefers json subtitles over srt", async ({ page }) => {
  const jsonName = "いえカノ～占い師の恋人と過ごすハッピーデイ～.json";
  const srtName = "いえカノ～占い師の恋人と過ごすハッピーデイ～.srt";
  const audioName = "いえカノ～占い師の恋人と過ごすハッピーデイ～.mp3";
  const imageName = "01.jpg";
  const jsonText = sentenceJson;
  const srtText = await readFile(`いえカノ/${srtName}`, "utf8");

  await page.addInitScript(({ jsonName, srtName, audioName, imageName, jsonText, srtText }) => {
    const writes = {};
    window.__writes = writes;

    const files = {
      [jsonName]: { text: jsonText, type: "application/json" },
      [srtName]: { text: srtText, type: "text/plain" },
      [audioName]: { bytes: new Uint8Array([0]), type: "audio/mpeg" },
      [imageName]: { bytes: new Uint8Array([0]), type: "image/jpeg" },
    };

    const makeEntry = (name) => ({
      kind: "file",
      name,
      async getFile() {
        const file = files[name];
        return new File([file.text ?? file.bytes], name, { type: file.type });
      },
    });

    window.showDirectoryPicker = async () => ({
      name: "いえカノ",
      async requestPermission() {
        return "granted";
      },
      async *values() {
        yield makeEntry(imageName);
        yield makeEntry(jsonName);
        yield makeEntry(audioName);
        yield makeEntry(srtName);
      },
      async getFileHandle(name, options = {}) {
        if (options.create && name.endsWith(".vc_json")) {
          return {
            async createWritable() {
              const chunks = [];
              return {
                async write(chunk) {
                  chunks.push(String(chunk));
                },
                async close() {
                  writes[name] = chunks.join("");
                },
              };
            },
          };
        }
        if (!files[name]) throw new DOMException(`Missing file: ${name}`, "NotFoundError");
        return {
          async getFile() {
            const file = files[name];
            return new File([file.text ?? file.bytes], name, { type: file.type });
          },
        };
      },
    });
  }, { jsonName, srtName, audioName, imageName, jsonText, srtText });

  await page.goto("/");
  await page.locator("button").first().click();

  await expect(page.locator(".folder-path").first()).toContainText("いえカノ");
  await expect.poll(() => page.evaluate(() => Object.keys(window.__writes))).toContain("いえカノ～占い師の恋人と過ごすハッピーデイ～.vc_json");
  await expect.poll(() => page.locator(".editor").evaluateAll((elements) => elements.map((element) => element.innerText.replace(/\u200B/g, "").replace(/\n$/, "")))).toContain("こんにちは。\n\nイエカノでーす。");
  const generated = await page.evaluate((name) => JSON.parse(window.__writes[name]), "いえカノ～占い師の恋人と過ごすハッピーデイ～.vc_json");
  expect(generated.scriptFiles[0].inlineData).toBeUndefined();
  expect(generated.scriptFiles[0].filePath).toBe(jsonName);
  expect(generated.scriptFiles[0].name).toBe(jsonName);
  expect(generated.srtFiles).toBeUndefined();
  expect(generated.jsonFiles).toBeUndefined();
});
