<script>
  import StyleRibbon from "./components/Style_Ribbon.svelte";
  import MediaPlayer from "./components/Media_Player.svelte";
  import SrtEditor from "./components/Srt_Editor.svelte";
  import { onMount, untrack } from "svelte";
  import { innerHeight } from "svelte/reactivity/window";
  import {
    addEditorColumn,
    addSubtitleTrack,
    clearOverlaySelection,
    editorLayoutState,
    mediaState,
    projectState,
    removeEditorColumn,
    setLoadedMedia,
    setProjectDataList,
    uiState,
    useAudio,
    useRefs,
  } from "./lib/store.svelte";
  import {
    createBlankSubtitleClip,
    createSubtitleMediaTrack,
    createSubtitleScriptFile,
    getAutoGeneratedVcJsonName,
    getDefaultJsonData,
    getDefaultMedia,
    getJsonDataList,
    getMedia,
    saveJsonFile,
    saveSubtitleFile,
    syncJsonDataFromMedia,
  } from "./lib/data_process";
  import Track from "./components/Track.svelte";
  import TrackView from "./components/Track_View.svelte";

  let dragging = $state(false);
  let startX = $state(0);
  let startWidth = $state();

  // トースト通知
  let toastMessage = $state('');
  let toastType = $state('');
  let toastTimer;
  function showToast(message, type = 'success') {
    toastMessage = message;
    toastType = type;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => { toastMessage = ''; }, 3000);
  }
  let json_data = $derived(projectState.jsonDataList[projectState.mediaIndex]);
  let mediaLoadToken = 0;
  let newTrackName = $state("");
  let newTrackFormat = $state("json");
  let mainRef = $state();

  // @ts-ignore
  $effect(async () => {
    const token = ++mediaLoadToken;
    // json_data / dirHandle の変化だけを追跡し、media への書き戻しで再実行しないよう untrack で退避
    const prevVol  = untrack(() => mediaState.media.volume);
    const prevRate = untrack(() => mediaState.media.playbackRate);
    try {
      const result = await getMedia(json_data, projectState.dirHandle);
      if (token !== mediaLoadToken) {
        if (result.audioUrl) URL.revokeObjectURL(result.audioUrl);
        return;
      }
      useAudio.set(result.audio ?? null, result.audioUrl ?? null);
      const { audio: _ignoredAudio, audioUrl: _ignoredUrl, ...rest } = result;
      setLoadedMedia(rest);
      useRefs.editorRefs = [];
      // メディア切り替え後も音量・倍速を維持
      useAudio.setVol(prevVol);
      useAudio.setRate(prevRate);
    } catch (err) {
      if (token !== mediaLoadToken) return;
      console.warn("メディア読み込みエラー:", err);
      useAudio.set(null);
      setLoadedMedia(getDefaultMedia());
    }
  });

  // UI部品まわりの変数
  let currentColumnIndex = $state(-1);

  const totalWidth = $derived.by(() => {
    return editorLayoutState.columns.reduce((sum, column) => sum + column.width, 0);
  });

  // trackRef のサイズ変化を ResizeObserver でリアクティブに追跡
  let trackHeight = $state(0);
  $effect(() => {
    const el = useRefs.trackRef;
    if (!el) return;
    const ro = new ResizeObserver(([entry]) => {
      trackHeight = entry.contentRect.height;
    });
    ro.observe(el);
    trackHeight = el.getBoundingClientRect().height;
    return () => ro.disconnect();
  });

  const tableHeight = $derived.by(() => {
    innerHeight.current;
    if (!mainRef || !useRefs.tableRef) return 120;
    const mainRect = mainRef.getBoundingClientRect();
    const tableRect = useRefs.tableRef.getBoundingClientRect();
    const mainStyle = getComputedStyle(mainRef);
    const paddingBottom = parseFloat(mainStyle.paddingBottom) || 0;
    const reservedTrackHeight = uiState.viewTrack
      ? Math.min(Math.max(trackHeight || 0, 70), 160)
      : 0;
    return Math.max(120, Math.floor(mainRect.bottom - tableRect.top - reservedTrackHeight - paddingBottom));
  });

  // メインモデルの監視用
  // $effect(() => {
  //   console.log("json_data_list:", $state.snapshot(json_data_list));
  //   console.log("media_index:", $state.snapshot(media_index));
  //   console.log("media:", $state.snapshot(media));
  //   console.log("style_list:", $state.snapshot(style_list));
  // });

  function stopAudio() {
    useAudio.stop();
  }

  // フォルダを読み込み、json_dataを作成
  async function handleLoad() {
    stopAudio();
    // @ts-ignore
    projectState.dirHandle = await window.showDirectoryPicker();

    // 書き込み権限をリクエスト
    const permission = await projectState.dirHandle.requestPermission({ mode: "readwrite" });

    if (permission !== "granted") {
      console.warn("書き込み権限が許可されませんでした。");
      return;
    }

    projectState.folderName = projectState.dirHandle.name;
    try {
      const result = await getJsonDataList(projectState.dirHandle);
      for (const data of result) {
        const generatedName = getAutoGeneratedVcJsonName(data);
        if (generatedName) {
          await saveJsonFile(projectState.dirHandle, generatedName, data);
        }
      }
      setProjectDataList(result);
      console.log("フォルダ読み込み完了：", result);
    } catch (err) {
      console.warn("読み込みエラー:", err);
      projectState.folderName = "";
    }
  }

  async function save_VC_JSON_File() {
    if (projectState.dirHandle && json_data?.name && json_data.name !== "dummy") {
      const nameWithoutExt = mediaState.media.name.replace(/\.[^/.]+$/, "");
      const name = `${nameWithoutExt}.vc_json`;

      const dataToSave = syncJsonDataFromMedia(json_data, mediaState.media);
      const success = await saveJsonFile(projectState.dirHandle, name, dataToSave);
      uiState.jsonSaveStatus = success ? 1 : -1;
      showToast(success ? 'vc_json 保存完了' : 'vc_json 保存失敗', success ? 'success' : 'error');

      // 1秒後にアイコンを通常に戻す
      setTimeout(() => {
        uiState.jsonSaveStatus = 0;
      }, 2000);
    }
  }

  async function save_SRT_Files() {
    let success = false;
    if (projectState.dirHandle) {
      console.log(mediaState.media);
      for (const srtfile of mediaState.media.srt_data.filter((track) => !track.isImageTrack)) {
        success = await saveSubtitleFile(projectState.dirHandle, srtfile.file_path || srtfile.name, srtfile.data);
        if (!success) break;
      }
      uiState.srtSaveStatus = success ? 1 : -1;
      showToast(success ? '字幕 保存完了' : '字幕 保存失敗', success ? 'success' : 'error');

      // 1秒後にアイコンを通常に戻す
      setTimeout(() => {
        uiState.srtSaveStatus = 0;
      }, 2000);
    }
  }

  function sanitizeTrackFileBase(name) {
    return String(name ?? "")
      .trim()
      .replace(/[\\/:*?"<>|]/g, "_")
      .replace(/^\.+/, "")
      .slice(0, 120);
  }

  function existingSubtitlePathSet() {
    return new Set((json_data?.scriptFiles ?? []).map((item) => String(item.filePath ?? item.name ?? "").toLowerCase()));
  }

  async function createSubtitleTrackFromUI() {
    if (!projectState.dirHandle || !json_data?.scriptFiles) {
      showToast("フォルダを読み込んでから作成してください。", "error");
      return;
    }
    const baseName = sanitizeTrackFileBase(newTrackName);
    if (!baseName) {
      showToast("字幕トラック名を入力してください。", "error");
      return;
    }
    const extension = newTrackFormat === "srt" ? "srt" : "json";
    const filePath = extension === "srt" ? `srt/${baseName}.srt` : `${baseName}.json`;
    if (existingSubtitlePathSet().has(filePath.toLowerCase())) {
      showToast("同じ字幕ファイル名が既にあります。", "error");
      return;
    }

    const id = json_data.scriptFiles.length;
    const defaultStyle = Object.keys(json_data.styles ?? {})[0] ?? "default-style-1";
    const data = [createBlankSubtitleClip(mediaState.media.duration)];
    const scriptFile = createSubtitleScriptFile({ filePath, name: filePath, defaultStyle });
    const track = createSubtitleMediaTrack({ id, name: filePath, filePath, data, defaultStyle });
    const subtitleSaved = await saveSubtitleFile(projectState.dirHandle, filePath, data);
    if (!subtitleSaved) {
      showToast("字幕トラック作成に失敗しました。", "error");
      return;
    }

    addSubtitleTrack(scriptFile, track);
    const vcJsonName = `${mediaState.media.name.replace(/\.[^/.]+$/, "")}.vc_json`;
    const vcSaved = await saveJsonFile(projectState.dirHandle, vcJsonName, syncJsonDataFromMedia(json_data, mediaState.media));
    newTrackName = "";
    showToast(vcSaved ? "字幕トラックを作成しました。" : "字幕は作成しましたが vc_json 保存に失敗しました。", vcSaved ? "success" : "error");
  }

  function scrollEditor() {
    for (const ref of useRefs.editorRefs) {
      console.log(ref);
      if (ref) {
        ref.scrollToIndex(json_data.seekTime);
      }
    }
  }

  function clearOverlaySelectionOutsideRibbon(event) {
    const target = event.target;
    if (target?.closest?.(".ribbonview")) return;
    if (target?.closest?.(".srt_box")) return;
    clearOverlaySelection();
    document.activeElement?.blur?.();
  }

  // ドラッグ開始
  const startDrag = (event, index) => {
    dragging = true;
    startX = event.clientX;
    currentColumnIndex = index;
    startWidth = editorLayoutState.columns[index]?.width;
    const newColumns = editorLayoutState.columns.map((column) => ({ ...column }));

    const totalWidth = editorLayoutState.columns.reduce((sum, column) => sum + column.width, 0);

    // ドラッグ中の処理
    const onMouseMove = (moveEvent) => {
      if (dragging) {
        const diff = moveEvent.clientX - startX;

        if (currentColumnIndex == -1) {
          const scale = (totalWidth - diff) / totalWidth; // 拡大なら scale > 1、縮小なら < 1
          editorLayoutState.columns = newColumns.map((column) => ({ ...column, width: Math.max(50, column.width * scale) }));
        } else {
          // 元の幅を複製してから調整

          const current = currentColumnIndex;
          const prev = current - 1;

          const newWidth = Math.max(50, startWidth - diff);
          // 現在列に delta を加える
          newColumns[current].width = newWidth;
          if (prev >= 0) {
            const delta = newWidth - editorLayoutState.columns[current].width;

            // 前の列から delta を引く
            newColumns[prev].width = Math.max(50, editorLayoutState.columns[prev].width - delta);
          }
          editorLayoutState.columns = newColumns;
        }
      }
    };

    // ドラッグ終了時の処理
    const stopDrag = () => {
      dragging = false;
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("mouseup", stopDrag);
    };

    // イベントリスナーを追加
    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", stopDrag);
  };

  onMount(() => {
    window.addEventListener("beforeunload", () => {
      useAudio.stop();
    });
  });
</script>

<main bind:this={mainRef} onmousedown={clearOverlaySelectionOutsideRibbon}>
  <div class="folder-path">{projectState.folderName}</div>
  <button class="nmorph_button" onclick={handleLoad}>
    <span class="material-symbols-outlined"> folder_open </span>
  </button>
  <button
    class="nmorph_button"
    disabled={projectState.mediaIndex <= 0}
    onclick={() => {
      if (projectState.mediaIndex > 0) {
        projectState.mediaIndex -= 1;
        stopAudio();
      }
    }}
  >
    ◀
  </button>

  <!-- <div class="folder-path">{media.name}</div> -->
  <select class="folder-path" bind:value={projectState.mediaIndex}>
    {#each projectState.jsonDataList as jsondata, index}
      <option value={index}>{jsondata.name}</option>
    {/each}
  </select>

  <button class="nmorph_button" title="vc_jsonを保存" onclick={save_VC_JSON_File}>
    {#if uiState.jsonSaveStatus == 0}
      <span class="material-symbols-outlined"> save_as </span>
    {:else if uiState.jsonSaveStatus > 0}
      <span class="material-symbols-outlined"> check </span>
    {:else}
      <span class="material-symbols-outlined"> error </span>
    {/if}
  </button>
  <button class="nmorph_button"
    disabled={projectState.mediaIndex >= projectState.jsonDataList.length - 1}
    onclick={() => {
      if (projectState.mediaIndex < projectState.jsonDataList.length - 1) {
        projectState.mediaIndex += 1;
        stopAudio();
      }
    }}>
    ▶
  </button>
  <span class="head-text">Edit Frame：</span>
  <label class="toggle_switch" title="字幕枠の編集ハンドル表示" style="margin-right: 5px;">
    <input type="checkbox" bind:checked={uiState.viewSrtFrame} style="visibility: hidden;" />
    <span class="toggle-slider"></span>
  </label>
  <div class="CheckButtonArea">
    <input type="checkbox" bind:checked={uiState.autoScroll} id="AutoScrollButton" />
    <label for="AutoScrollButton"><span>Auto Scroll</span></label>
  </div>

  <span class="head-text">View Ribbon：</span>
  <label class="toggle_switch" style="margin-right: 5px;">
    <input type="checkbox" bind:checked={uiState.viewRibbon} style="visibility: hidden;" />
    <span class="toggle-slider"></span>
  </label>
  {#if uiState.viewRibbon}
    <StyleRibbon></StyleRibbon>
  {/if}

  {#if toastMessage}
    <div class="toast toast-{toastType}">{toastMessage}</div>
  {/if}
  {#if projectState.jsonDataList.length > projectState.mediaIndex && json_data?.styles}
    <table style="width: 100%; height: {tableHeight}px;" bind:this={useRefs.tableRef} cellspacing="0" cellpadding="0">
      <tbody>
        <tr>
          <!-- 🎬 左側：メディアプレイヤー -->
          <td>
            {#if mediaState.media}
              <MediaPlayer />
            {/if}
          </td>

          <!-- 🟦 リサイズバー -->
          <td style="width: 5px;">
            <div class="resizer" role="button" tabindex="-1" style="cursor: ew-resize; height: 100%;" onmousedown={(event) => startDrag(event, -1)}></div>
          </td>

          <!-- 📝 右側：編集エリア（ネストテーブル）-->
          <td style="width:{totalWidth}px; vertical-align: top;">
            <table class="srt_area" style="width: 100%; height: 100%;" cellspacing="0" cellpadding="0">
              <tbody>
                <!-- 上部操作エリア -->
                <tr>
                  <td colspan={editorLayoutState.columns.length} style="height: 30px;">
                    <button class="nmorph_button" style="margin-left:15px;" onclick={removeEditorColumn}>◀</button>
                    <span>{editorLayoutState.columns.length}</span>
                    <button class="nmorph_button" onclick={addEditorColumn}>▶</button>
                        <button class="nmorph_button" onclick={scrollEditor} title="再生位置にスクロール"> Scroll </button>
                    <input class="new-track-name" data-testid="new-subtitle-track-name" type="text" bind:value={newTrackName} placeholder="new subtitle" />
                    <select class="new-track-format" data-testid="new-subtitle-track-format" bind:value={newTrackFormat}>
                      <option value="json">json</option>
                      <option value="srt">srt</option>
                    </select>
                    <button class="nmorph_button" data-testid="create-subtitle-track" onclick={createSubtitleTrackFromUI} title="字幕トラックを作成">
                      <span class="material-symbols-outlined"> add </span>
                    </button>
                    <button class="nmorph_button" onclick={save_SRT_Files} title="字幕を保存">
                      {#if uiState.srtSaveStatus == 0}
                        <span class="material-symbols-outlined"> save_as </span>
                      {:else if uiState.srtSaveStatus > 0}
                        <span class="material-symbols-outlined"> check </span>
                      {:else}
                        <span class="material-symbols-outlined"> error </span>
                      {/if}
                    </button>
                  </td>
                </tr>

                <!-- 各列（字幕編集欄） -->
                <tr>
                  {#each editorLayoutState.columns as column, index (column.id)}
                    <td style="width: {column.width}px; position: relative; height: 100%;">
                      <div style="display: flex; height: 100%;">
                        <div class="resize-bar" role="button" tabindex="-1" onmousedown={(event) => startDrag(event, index)}></div>
                        <div style="flex-grow: 1; height: 100%;">
                          <SrtEditor bind:this={useRefs.editorRefs[index]} parents_height={tableHeight} column={column} style="height: 100%;" />
                        </div>
                      </div>
                    </td>
                  {/each}
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>

    {#if uiState.viewTrack}
      <TrackView></TrackView>
    {/if}
  {/if}
</main>

<style>
  main {
    padding: 10px;
    height: 100dvh;
    box-sizing: border-box;
    overflow: hidden;
  }
  .folder-path {
    margin: 5px;
    display: inline-block;
    padding: 1px 10px;
    min-width: 300px;
    max-width: 600px;
    height: 25px;
    vertical-align: middle;
    align-content: center;
    font-size: 15px;
    border-radius: 5px;
    color: #000000;
    background: #a7a7a7c5;
    box-shadow:
      inset 4px 5px 10px #0000008e,
      inset -4px -4px 15px #ffffff28;

    overflow-x: auto;
    white-space: nowrap;
    cursor: text; /* ← テキストっぽい見た目に */

    /* スクロールバー非表示 */
    scrollbar-width: none; /* Firefox */
    -ms-overflow-style: none; /* IE/Edge */

    user-select: text;
  }
  .folder-path::-webkit-scrollbar {
    display: none; /* Chrome/Safari */
  }

  .resizer {
    align-self: center;
    position: relative;
    cursor: ew-resize;
    background-color: rgba(231, 0, 0, 0); /* 背景透明感を調整 */
    width: 11px;
    height: 95%;
    margin: 0;
    padding: 0;
    flex-shrink: 0;
    /* display: inline-block; */
  }

  .resize-bar {
    align-self: center;
    position: relative;
    cursor: col-resize;
    background-color: rgba(0, 0, 0, 0); /* 背景透明感を調整 */
    width: 14px;
    height: 95%;
    margin: 0;
    padding: 0;
    flex-shrink: 0;
    align-content: center;
    /* display: inline-block; */
  }
  /* 中心線を描画 */
  .resize-bar::before,
  .resize-bar::after {
    content: "";
    position: absolute;
    width: 1px;
    height: 30px;
    border-radius: 4px;
    left: 4px;
    background-color: #505050fd;
    pointer-events: none; /* クリックを通す */
    box-shadow: -1px -1px 1px #b8b8b82c;
  }

  .new-track-name {
    width: 130px;
    height: 25px;
    box-sizing: border-box;
    margin-left: 10px;
    color: #d6d6d6;
    background-color: #42424279;
    border: 1px solid #a3a3a349;
    border-radius: 4px;
  }
  .new-track-format {
    height: 25px;
    color: #d6d6d6;
    background-color: #42424279;
    border: 1px solid #a3a3a349;
    border-radius: 4px;
  }
  .resize-bar::after {
    transform: translateX(4px);
  }

  .material-symbols-outlined {
    font-size: 18px;
    vertical-align: middle;
    font-variation-settings:
      "FILL" 1,
      "wght" 400,
      "GRAD" 0,
      "opsz" 48;
  }
  .srt_area {
    box-sizing: border-box;
    padding: 10px 15px 0px 3px;
    background-color: #0e0e0e52;
    /* border: 1px solid #ff0a0a; */

    box-shadow:
      inset 5px 10px 15px rgba(5, 5, 5, 0.712),
      inset -5px -5px 8px #dbdbdb21;
    border-radius: 8px;
  }
  table {
    overflow: hidden;
  }

  /* === ボタンを表示するエリア ============================== */
  .CheckButtonArea {
    margin: 3px 0px 3px 10px;
    display: inline-block;
  }

  /* === チェックボックス ==================================== */
  .CheckButtonArea input[type="checkbox"] {
    display: none; /* チェックボックス非表示 */
  }

  /* === チェックボックスのラベル（標準） ==================== */
  .CheckButtonArea label {
    display: block; /* ボックス要素に変更 */
    text-align: center; /* 文字位置は中央     */
    align-content: center;
    border-radius: 5px; /* 角丸               */
    height: 25px; /* ボタンの高さ       */
    font-size: 15px; /* 文字サイズ         */
    transition: 0.1s; /* ゆっくり変化       */

    color: #8d8d8d;
    margin: 5px 0px;
    padding: 0px 10px;
    background: #29292b;
    cursor: pointer;
    /* border: 1px solid #29292b; */
    transition: all 0.1s;
    box-shadow:
      4px 4px 8px #020202a4,
      -4px -4px 8px #434346;
  }

  /* === ON側のチェックボックスのラベル（ONのとき） ========== */
  .CheckButtonArea label span:after {
    color: rgb(255, 255, 255);
  }
  .CheckButtonArea input[type="checkbox"]:checked + label {
    color: #1c9199c0;
    background: #00000067;
    box-shadow:
      inset 4px 4px 8px #000000d3,
      inset -4px -4px 8px #70707067;
  }
  .CheckButtonArea input[type="checkbox"]:checked + label span:after {
    color: #fff; /* 文字色             */
  }

  /* トースト通知 */
  .toast {
    position: fixed;
    bottom: 24px;
    right: 24px;
    padding: 10px 18px;
    border-radius: 6px;
    font-size: 14px;
    z-index: 9999;
    pointer-events: none;
    animation: toast-in 0.2s ease;
  }
  .toast-success { background: #1a5c3a; color: #b8f5d0; }
  .toast-error   { background: #6b1a1a; color: #ffd6d6; }
  @keyframes toast-in {
    from { opacity: 0; transform: translateY(8px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  /* 非活性ボタン */
  button:disabled {
    opacity: 0.3;
    cursor: not-allowed;
  }
</style>
