<script>
  import StyleRibbon from "./components/Style_Ribbon.svelte";
  import MediaPlayer from "./components/Media_Player.svelte";
  import SrtEditor from "./components/Srt_Editor.svelte";
  import { onMount, untrack } from "svelte";
  import {
    addEditorColumn,
    addSubtitleTrack,
    clearOverlaySelection,
    editorLayoutState,
    mediaState,
    projectState,
    removeEditorColumn,
    setLoadedMedia,
    setProjectDataList,
    uiState,
    useAudio,
    useRefs,
  } from "./lib/store.svelte";
  import {
    createBlankSubtitleClip,
    createSubtitleMediaTrack,
    createSubtitleScriptFile,
    getAutoGeneratedVcJsonName,
    getDefaultMedia,
    getJsonDataList,
    getMedia,
    saveJsonFile,
    saveSubtitleFile,
    syncJsonDataFromMedia,
  } from "./lib/data_process";
  import TrackView from "./components/Track_View.svelte";

  let dragging = $state(false);
  let startX = $state(0);
  let startWidth = $state();

  // トースト通知
  let toastMessage = $state('');
  let toastType = $state('');
  let toastTimer;
  function showToast(message, type = 'success') {
    toastMessage = message;
    toastType = type;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => { toastMessage = ''; }, 3000);
  }
  let json_data = $derived(projectState.jsonDataList[projectState.mediaIndex]);
  let showQuickStart = $derived(!projectState.dirHandle);
  let mediaLoadToken = 0;
  let newTrackName = $state("");
  let newTrackFormat = $state("json");
  let mainRef = $state();

  // @ts-ignore
  $effect(async () => {
    const token = ++mediaLoadToken;
    // json_data / dirHandle の変化だけを追跡し、media への書き戻しで再実行しないよう untrack で退避
    const prevVol  = untrack(() => mediaState.media.volume);
    const prevRate = untrack(() => mediaState.media.playbackRate);
    try {
      const result = await getMedia(json_data, projectState.dirHandle);
      if (token !== mediaLoadToken) {
        // 古くなった（破棄される）結果の blob URL を解放してリークを防ぐ
        if (result.audioUrl) URL.revokeObjectURL(result.audioUrl);
        const staleImage = result.image_data?.currentImage;
        if (staleImage && typeof staleImage === "string" && staleImage.startsWith("blob:")) URL.revokeObjectURL(staleImage);
        return;
      }
      useAudio.set(result.audio ?? null, result.audioUrl ?? null);
      const { audio: _ignoredAudio, audioUrl: _ignoredUrl, ...rest } = result;
      setLoadedMedia(rest);
      useRefs.editorRefs = [];
      // メディア切り替え後も音量・倍速を維持
      useAudio.setVol(prevVol);
      useAudio.setRate(prevRate);
    } catch (err) {
      if (token !== mediaLoadToken) return;
      console.warn("メディア読み込みエラー:", err);
      useAudio.set(null);
      setLoadedMedia(getDefaultMedia());
    }
  });

  // UI部品まわりの変数
  let currentColumnIndex = $state(-1);

  const totalWidth = $derived.by(() => {
    return editorLayoutState.columns.reduce((sum, column) => sum + column.width, 0);
  });

  // レイアウト高さは CSS（flex の min-height:0 連鎖）で解決するため、
  // 旧来の getBoundingClientRect ベースの tableHeight 計算は廃止した。

  // メインモデルの監視用
  // $effect(() => {
  //   console.log("json_data_list:", $state.snapshot(json_data_list));
  //   console.log("media_index:", $state.snapshot(media_index));
  //   console.log("media:", $state.snapshot(media));
  //   console.log("style_list:", $state.snapshot(style_list));
  // });

  function stopAudio() {
    useAudio.stop();
  }

  // フォルダを読み込み、json_dataを作成
  async function handleLoad() {
    stopAudio();
    // @ts-ignore
    projectState.dirHandle = await window.showDirectoryPicker();

    // 書き込み権限をリクエスト
    const permission = await projectState.dirHandle.requestPermission({ mode: "readwrite" });

    if (permission !== "granted") {
      console.warn("書き込み権限が許可されませんでした。");
      return;
    }

    projectState.folderName = projectState.dirHandle.name;
    try {
      const result = await getJsonDataList(projectState.dirHandle);
      for (const data of result) {
        const generatedName = getAutoGeneratedVcJsonName(data);
        if (generatedName) {
          await saveJsonFile(projectState.dirHandle, generatedName, data);
        }
      }
      setProjectDataList(result);
      console.log("フォルダ読み込み完了：", result);
    } catch (err) {
      console.warn("読み込みエラー:", err);
      projectState.folderName = "";
    }
  }

  async function save_VC_JSON_File() {
    if (projectState.dirHandle && json_data?.name && json_data.name !== "dummy") {
      const nameWithoutExt = mediaState.media.name.replace(/\.[^/.]+$/, "");
      const name = `${nameWithoutExt}.vc_json`;

      const dataToSave = syncJsonDataFromMedia(json_data, mediaState.media);
      const success = await saveJsonFile(projectState.dirHandle, name, dataToSave);
      uiState.jsonSaveStatus = success ? 1 : -1;
      showToast(success ? 'vc_json 保存完了' : 'vc_json 保存失敗', success ? 'success' : 'error');

      // 1秒後にアイコンを通常に戻す
      setTimeout(() => {
        uiState.jsonSaveStatus = 0;
      }, 2000);
    }
  }

  async function save_SRT_Files() {
    let success = false;
    if (projectState.dirHandle) {
      for (const srtfile of mediaState.media.srt_data.filter((track) => !track.isImageTrack)) {
        success = await saveSubtitleFile(projectState.dirHandle, srtfile.file_path || srtfile.name, srtfile.data);
        if (!success) break;
      }
      uiState.srtSaveStatus = success ? 1 : -1;
      showToast(success ? '字幕 保存完了' : '字幕 保存失敗', success ? 'success' : 'error');

      // 1秒後にアイコンを通常に戻す
      setTimeout(() => {
        uiState.srtSaveStatus = 0;
      }, 2000);
    }
  }

  function sanitizeTrackFileBase(name) {
    return String(name ?? "")
      .trim()
      .replace(/[\\/:*?"<>|]/g, "_")
      .replace(/^\.+/, "")
      .slice(0, 120);
  }

  function existingSubtitlePathSet() {
    return new Set((json_data?.scriptFiles ?? []).map((item) => String(item.filePath ?? item.name ?? "").toLowerCase()));
  }

  async function createSubtitleTrackFromUI() {
    if (!projectState.dirHandle || !json_data?.scriptFiles) {
      showToast("フォルダを読み込んでから作成してください。", "error");
      return;
    }
    const baseName = sanitizeTrackFileBase(newTrackName);
    if (!baseName) {
      showToast("字幕トラック名を入力してください。", "error");
      return;
    }
    const extension = newTrackFormat === "srt" ? "srt" : "json";
    const filePath = extension === "srt" ? `srt/${baseName}.srt` : `${baseName}.json`;
    if (existingSubtitlePathSet().has(filePath.toLowerCase())) {
      showToast("同じ字幕ファイル名が既にあります。", "error");
      return;
    }

    const id = json_data.scriptFiles.length;
    const defaultStyle = Object.keys(json_data.styles ?? {})[0] ?? "default-style-1";
    const data = [createBlankSubtitleClip(mediaState.media.duration)];
    const scriptFile = createSubtitleScriptFile({ filePath, name: filePath, defaultStyle });
    const track = createSubtitleMediaTrack({ id, name: filePath, filePath, data, defaultStyle });
    const subtitleSaved = await saveSubtitleFile(projectState.dirHandle, filePath, data);
    if (!subtitleSaved) {
      showToast("字幕トラック作成に失敗しました。", "error");
      return;
    }

    addSubtitleTrack(scriptFile, track);
    const vcJsonName = `${mediaState.media.name.replace(/\.[^/.]+$/, "")}.vc_json`;
    const vcSaved = await saveJsonFile(projectState.dirHandle, vcJsonName, syncJsonDataFromMedia(json_data, mediaState.media));
    newTrackName = "";
    showToast(vcSaved ? "字幕トラックを作成しました。" : "字幕は作成しましたが vc_json 保存に失敗しました。", vcSaved ? "success" : "error");
  }

  function scrollEditor() {
    window.dispatchEvent(new CustomEvent("srt-editor-scroll-current", { detail: { time: json_data.seekTime } }));
    for (const ref of useRefs.editorRefs) {
      if (ref) {
        ref.scrollToIndex(json_data.seekTime);
      }
    }
  }

  function clearOverlaySelectionOutsideRibbon(event) {
    const target = event.target;
    if (target?.closest?.(".ribbonview")) return;
    if (target?.closest?.(".srt_box")) return;
    clearOverlaySelection();
    document.activeElement?.blur?.();
  }

  // ドラッグ開始
  const startDrag = (event, index) => {
    dragging = true;
    startX = event.clientX;
    currentColumnIndex = index;
    startWidth = editorLayoutState.columns[index]?.width;
    const newColumns = editorLayoutState.columns.map((column) => ({ ...column }));

    const totalWidth = editorLayoutState.columns.reduce((sum, column) => sum + column.width, 0);

    // ドラッグ中の処理（newColumns はドラッグ開始時のスナップショット。
    // ライブ state を読まずスナップショットから計算することで、移動中の累積誤差を防ぐ）
    const onMouseMove = (moveEvent) => {
      if (!dragging) return;
      const diff = moveEvent.clientX - startX;

      if (currentColumnIndex === -1) {
        // プレイヤー↔エディタ全体の境界: 全列を比率で拡縮
        const scale = (totalWidth - diff) / totalWidth;
        editorLayoutState.columns = newColumns.map((column) => ({ ...column, width: Math.max(50, column.width * scale) }));
        return;
      }

      const current = currentColumnIndex;
      const prev = current - 1;
      if (prev < 0) {
        // 先頭列: 隣接列が無いので単独で拡縮
        editorLayoutState.columns = newColumns.map((column, i) =>
          i === current ? { ...column, width: Math.max(50, newColumns[current].width - diff) } : { ...column },
        );
        return;
      }

      // 隣接列との境界: prev+current の合計を保ったまま再配分（合計幅がドラッグ中に増減しない）
      const pair = newColumns[prev].width + newColumns[current].width;
      const newCurrent = Math.max(50, Math.min(newColumns[current].width - diff, pair - 50));
      editorLayoutState.columns = newColumns.map((column, i) => {
        if (i === current) return { ...column, width: newCurrent };
        if (i === prev) return { ...column, width: pair - newCurrent };
        return { ...column };
      });
    };

    // ドラッグ終了時の処理
    const stopDrag = () => {
      dragging = false;
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("mouseup", stopDrag);
    };

    // イベントリスナーを追加
    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", stopDrag);
  };

  onMount(() => {
    window.addEventListener("beforeunload", () => {
      useAudio.stop();
    });
  });
</script>

<main bind:this={mainRef} onmousedown={clearOverlaySelectionOutsideRibbon}>
  <header class="app-toolbar">
    <div class="folder-path">{projectState.folderName}</div>

    <div class="toolbar-group">
      <button class="nmorph_button" title="フォルダを開く" aria-label="フォルダを開く" onclick={handleLoad}>
        <span class="material-symbols-outlined"> folder_open </span>
      </button>
      <button
        class="nmorph_button"
        title="前のメディア"
        aria-label="前のメディア"
        disabled={projectState.mediaIndex <= 0}
        onclick={() => {
          if (projectState.mediaIndex > 0) {
            projectState.mediaIndex -= 1;
            stopAudio();
          }
        }}
      >
        <span class="material-symbols-outlined"> chevron_left </span>
      </button>
      <select class="folder-path media-select" aria-label="メディア選択" bind:value={projectState.mediaIndex}>
        {#each projectState.jsonDataList as jsondata, index}
          <option value={index}>{jsondata.name}</option>
        {/each}
      </select>
      <button
        class="nmorph_button"
        title="次のメディア"
        aria-label="次のメディア"
        disabled={projectState.mediaIndex >= projectState.jsonDataList.length - 1}
        onclick={() => {
          if (projectState.mediaIndex < projectState.jsonDataList.length - 1) {
            projectState.mediaIndex += 1;
            stopAudio();
          }
        }}
      >
        <span class="material-symbols-outlined"> chevron_right </span>
      </button>
      <button class="nmorph_button" title="vc_jsonを保存" aria-label="vc_jsonを保存" onclick={save_VC_JSON_File}>
        {#if uiState.jsonSaveStatus == 0}
          <span class="material-symbols-outlined"> save_as </span>
        {:else if uiState.jsonSaveStatus > 0}
          <span class="material-symbols-outlined"> check </span>
        {:else}
          <span class="material-symbols-outlined"> error </span>
        {/if}
      </button>
    </div>

    <div class="toolbar-group toggles">
      <label class="toggle-field" title="字幕枠の編集ハンドル表示">
        <span class="head-text">Edit Frame</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.viewSrtFrame} />
          <span class="toggle-slider"></span>
        </span>
      </label>
      <label class="toggle-field" title="再生に追従して字幕エディタをスクロール">
        <span class="head-text">Auto Scroll</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.autoScroll} id="AutoScrollButton" />
          <span class="toggle-slider"></span>
        </span>
      </label>
      <label class="toggle-field" title="スタイルリボンの表示">
        <span class="head-text">Ribbon</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.viewRibbon} />
          <span class="toggle-slider"></span>
        </span>
      </label>
      <label class="toggle-field" title="タイムラインの表示">
        <span class="head-text">Timeline</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.viewTrack} />
          <span class="toggle-slider"></span>
        </span>
      </label>
    </div>
  </header>

  {#if showQuickStart}
    <section class="quick-start" aria-label="使い方">
      <div class="quick-start-title">
        <span class="material-symbols-outlined">info</span>
        <span>使い方</span>
      </div>
      <ol>
        <li><span>1</span>フォルダを開く</li>
        <li><span>2</span>メディアを選ぶ</li>
        <li><span>3</span>字幕を編集して保存</li>
      </ol>
    </section>
  {/if}

  {#if uiState.viewRibbon}
    <StyleRibbon></StyleRibbon>
  {/if}

  {#if toastMessage}
    <div class="toast toast-{toastType}">{toastMessage}</div>
  {/if}
  {#if projectState.jsonDataList.length > projectState.mediaIndex && json_data?.styles}
    <section class="workspace-table" bind:this={useRefs.tableRef}>
      <!-- 左: メディアプレイヤー -->
      <div class="player-pane">
        {#if mediaState.media}
          <MediaPlayer />
        {/if}
      </div>

      <!-- リサイズバー（プレイヤー↔編集エリア） -->
      <div class="resizer" role="button" tabindex="-1" aria-label="プレイヤーと編集エリアの境界" onmousedown={(event) => startDrag(event, -1)}></div>

      <!-- 右: 編集エリア（列の合計幅 totalWidth に左右パディング分を足した値を上限にし、
           プレイヤーとの取り合いで幅が足りない時は縮小＋内部横スクロールで収める） -->
      <div class="srt_area" style="max-width: calc({totalWidth}px + 30px);">
        <div class="editor-toolbar">
          <button class="nmorph_button" title="列を減らす" aria-label="列を減らす" onclick={removeEditorColumn}>
            <span class="material-symbols-outlined"> chevron_left </span>
          </button>
          <span class="col-count">{editorLayoutState.columns.length}</span>
          <button class="nmorph_button" title="列を増やす" aria-label="列を増やす" onclick={addEditorColumn}>
            <span class="material-symbols-outlined"> chevron_right </span>
          </button>
          <button class="nmorph_button" onclick={scrollEditor} title="再生位置にスクロール"> Scroll </button>
          <span class="toolbar-spacer"></span>
          <input class="new-track-name" data-testid="new-subtitle-track-name" type="text" bind:value={newTrackName} placeholder="new subtitle" />
          <select class="new-track-format" data-testid="new-subtitle-track-format" bind:value={newTrackFormat}>
            <option value="json">json</option>
            <option value="srt">srt</option>
          </select>
          <button class="nmorph_button" data-testid="create-subtitle-track" onclick={createSubtitleTrackFromUI} title="字幕トラックを作成" aria-label="字幕トラックを作成">
            <span class="material-symbols-outlined"> playlist_add </span>
          </button>
          <button class="nmorph_button" onclick={save_SRT_Files} title="字幕を保存" aria-label="字幕を保存">
            {#if uiState.srtSaveStatus == 0}
              <span class="material-symbols-outlined"> save_as </span>
            {:else if uiState.srtSaveStatus > 0}
              <span class="material-symbols-outlined"> check </span>
            {:else}
              <span class="material-symbols-outlined"> error </span>
            {/if}
          </button>
        </div>

        <div class="editor-columns">
          {#each editorLayoutState.columns as column, index (column.id)}
            <div class="editor-column" style="width: {column.width}px;">
              <div class="resize-bar" role="button" tabindex="-1" aria-label="列幅の調整" onmousedown={(event) => startDrag(event, index)}></div>
              <div class="editor-column-body">
                <SrtEditor bind:this={useRefs.editorRefs[index]} column={column} />
              </div>
            </div>
          {/each}
        </div>
      </div>
    </section>

    {#if uiState.viewTrack}
      <TrackView></TrackView>
    {/if}
  {/if}
</main>

<style>
  main {
    padding: 8px 12px 6px;
    height: 100dvh;
    box-sizing: border-box;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  /* ── 上部ツールバー（折り返し対応・グループ化） ── */
  .app-toolbar {
    flex: 0 0 auto;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 6px 12px;
    padding: 2px 0 4px;
  }
  .toolbar-group {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 4px;
  }
  .toolbar-group.toggles {
    gap: 6px 14px;
    margin-left: auto;
  }
  .toggle-field {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    cursor: pointer;
    white-space: nowrap;
    color: #c5d0d2;
  }
  .toggle-field .head-text {
    margin: 0;
    color: #27b1b5;
    font-size: 14px;
  }
  .toggle_switch input {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    margin: 0;
    opacity: 0;
    cursor: pointer;
  }
  .media-select {
    min-width: 160px;
    max-width: 340px;
    color: #dbe4e5;
    cursor: pointer;
  }

  /* ── ワークスペース（プレイヤー | 編集エリア） ── */
  .workspace-table {
    flex: 1 1 auto;
    min-height: 120px; /* 旧 tableHeight の Math.max(120, ...) と同じ下限を維持する */
    display: flex;
    align-items: stretch;
    width: 100%;
  }
  .player-pane {
    flex: 1 1 0;
    min-width: 220px; /* プレイヤーが0幅まで潰れて操作不能にならないための下限 */
    min-height: 0;
    display: flex;
  }
  .player-pane > :global(.media-player) {
    flex: 1 1 auto;
    min-width: 0;
    min-height: 0;
  }

  /* ── 編集エリア内 ── */
  .editor-toolbar {
    flex: 0 0 auto;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 4px;
    min-height: 42px;
    padding: 2px 4px 8px;
    border-bottom: 1px solid #313638;
  }
  .editor-toolbar .toolbar-spacer {
    flex: 1 1 auto;
  }
  .col-count {
    min-width: 18px;
    text-align: center;
    color: #b4b4b4;
  }
  .editor-columns {
    flex: 1 1 auto;
    min-height: 0;
    min-width: 0; /* overflow-x を効かせるため、内容幅で親を押し広げないようにする */
    display: flex;
    align-items: stretch;
    overflow-x: auto; /* 列合計幅が収まりきらない時は内部横スクロールで到達可能にする */
  }
  .editor-column {
    position: relative;
    display: flex;
    min-height: 0;
    flex: 0 0 auto;
  }
  .editor-column-body {
    flex: 1 1 auto;
    min-width: 0;
    min-height: 0;
    display: flex;
  }
  .editor-column-body > :global(.srt-editor) {
    flex: 1 1 auto;
    min-width: 0;
  }

  .folder-path {
    margin: 3px 6px 3px 0;
    display: inline-block;
    padding: 2px 10px;
    min-width: 300px;
    max-width: 600px;
    height: 25px;
    vertical-align: middle;
    align-content: center;
    font-size: 15px;
    border-radius: 5px;
    color: #dbe4e5;
    background: #1d2022;
    border: 1px solid #3d4547;
    box-shadow: inset 0 1px 0 #ffffff12;

    overflow-x: auto;
    white-space: nowrap;
    cursor: default;

    /* スクロールバー非表示 */
    scrollbar-width: none; /* Firefox */
    -ms-overflow-style: none; /* IE/Edge */

    user-select: text;
  }
  .folder-path::-webkit-scrollbar {
    display: none; /* Chrome/Safari */
  }

  .resizer {
    flex: 0 0 11px;
    align-self: stretch;
    position: relative;
    cursor: ew-resize;
    background-color: transparent;
    margin: 0;
    padding: 0;
  }

  .resize-bar {
    flex: 0 0 14px;
    align-self: stretch;
    position: relative;
    cursor: col-resize;
    background-color: transparent;
    margin: 0;
    padding: 0;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  /* 中心線を描画 */
  .resize-bar::before,
  .resize-bar::after {
    content: "";
    position: absolute;
    width: 1px;
    height: 30px;
    border-radius: 4px;
    left: 4px;
    background-color: #505050fd;
    pointer-events: none; /* クリックを通す */
    box-shadow: -1px -1px 1px #b8b8b82c;
  }

  .new-track-name {
    width: 130px;
    height: 25px;
    box-sizing: border-box;
    margin-left: 10px;
    color: #d6d6d6;
    background-color: #42424279;
    border: 1px solid #a3a3a349;
    border-radius: 4px;
  }
  .new-track-format {
    height: 25px;
    color: #d6d6d6;
    background-color: #42424279;
    border: 1px solid #a3a3a349;
    border-radius: 4px;
  }
  .resize-bar::after {
    transform: translateX(4px);
  }

  .material-symbols-outlined {
    font-size: 18px;
    vertical-align: middle;
    font-variation-settings:
      "FILL" 1,
      "wght" 400,
      "GRAD" 0,
      "opsz" 48;
  }
  .srt_area {
    flex: 0 1 auto; /* 列合計幅までは伸びるが、プレイヤー側が足りない時は縮小を許可する */
    min-width: 200px; /* 縮小してもツールバーのボタン類が残る最低限の幅 */
    min-height: 0;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    padding: 8px 8px 7px;
    background-color: #1a1b1d;
    border: 1px solid #2f3437;
    box-shadow: 0 8px 18px #00000055;
    border-radius: 8px;
  }

  .quick-start {
    flex: 0 0 auto;
    display: flex;
    align-items: center;
    gap: 18px;
    min-height: 40px;
    padding: 6px 12px;
    border: 1px solid #334245;
    border-radius: 6px;
    background: #202426;
    color: #cbd5d7;
  }
  .quick-start-title {
    display: inline-flex;
    align-items: center;
    gap: 7px;
    color: #2cc5c5;
    font-weight: 600;
    white-space: nowrap;
  }
  .quick-start-title .material-symbols-outlined {
    font-size: 18px;
  }
  .quick-start ol {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 10px 16px;
    margin: 0;
    padding: 0;
    list-style: none;
    font-size: 13px;
  }
  .quick-start li {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    white-space: nowrap;
  }
  .quick-start li span {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: #2e3d40;
    color: #bfeeee;
    font-size: 12px;
  }

  /* トースト通知 */
  .toast {
    position: fixed;
    bottom: 24px;
    right: 24px;
    padding: 10px 18px;
    border-radius: 6px;
    font-size: 14px;
    z-index: 9999;
    pointer-events: none;
    animation: toast-in 0.2s ease;
  }
  .toast-success { background: #1a5c3a; color: #b8f5d0; }
  .toast-error   { background: #6b1a1a; color: #ffd6d6; }
  @keyframes toast-in {
    from { opacity: 0; transform: translateY(8px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  /* 非活性ボタン */
  button:disabled {
    opacity: 0.3;
    cursor: not-allowed;
  }
</style>
