<script>
  import StyleRibbon from "./components/Style_Ribbon.svelte";
  import MediaPlayer from "./components/Media_Player.svelte";
  import SrtEditor from "./components/Srt_Editor.svelte";
  import { onMount, untrack } from "svelte";
  import {
    addEditorColumn,
    addSubtitleTrack,
    clearOverlaySelection,
    editorLayoutState,
    mediaState,
    projectState,
    removeEditorColumn,
    selectEditorClip,
    selectOverlayTrack,
    setLoadedMedia,
    setProjectDataList,
    uiState,
    useAudio,
    useRefs,
  } from "./lib/store.svelte";
  import {
    createBlankSubtitleClip,
    createSubtitleFile,
    createSubtitleMediaTrack,
    createSubtitleScriptFile,
    getAutoGeneratedVcJsonName,
    getDefaultMedia,
    getJsonDataList,
    getMedia,
    removeCreatedSubtitleFile,
    saveJsonFile,
    saveSubtitleTrack,
    syncJsonDataFromMedia,
  } from "./lib/data_process";
  import TrackView from "./components/Track_View.svelte";
  import WorkspaceControls from "./components/Workspace_Controls.svelte";
  import { getFileFromPath } from "./lib/util";
  import { editClips, forkEditorHistory } from "./lib/editor_history";
  import { splitSubtitleBlock } from "./lib/block_editing";
  import {
    hasUnsavedChanges, markProjectSaved, markTrackSaved, projectSnapshot,
    registerLoadedMedia, rememberMedia, resetProjectSessions, restoreMediaDraft, trackSnapshot,
  } from "./lib/project_session.js";

  let dragging = $state(false);
  let startX = $state(0);
  let startWidth = $state();
  let trackView = $state.raw(null);

  // トースト通知
  let toastMessage = $state('');
  let toastType = $state('');
  let toastTimer;
  function showToast(message, type = 'success') {
    toastMessage = message;
    toastType = type;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => { toastMessage = ''; }, 3000);
  }
  let json_data = $derived(projectState.jsonDataList[projectState.mediaIndex]);
  let showQuickStart = $derived(!projectState.dirHandle);
  let mediaLoadToken = 0;
  let newTrackName = $state("");
  let newTrackFormat = $state("json");
  let loading = $state(false);
  let saving = $state(false);
  let creating = $state(false);
  let convertingTrack = $state(false);
  let loadedProject = $state.raw(null);
  let preparedMedia = null;

  function flushEditor() {
    window.dispatchEvent(new CustomEvent("srt-editor-flush"));
  }

  // @ts-ignore
  $effect(() => {
    const data = json_data;
    const directory = projectState.dirHandle;
    const token = ++mediaLoadToken;
    // json_data / dirHandle の変化だけを追跡し、media への書き戻しで再実行しないよう untrack で退避
    const prevVol  = untrack(() => mediaState.media.volume);
    const prevRate = untrack(() => mediaState.media.playbackRate);
    untrack(() => {
      flushEditor();
      if (loadedProject) rememberMedia(loadedProject, mediaState.media);
      useAudio.pause();
      loading = true;
    });
    const ready = preparedMedia;
    preparedMedia = null;
    untrack(async () => {
    try {
      const result = await (ready ?? getMedia(data, directory));
      if (token !== mediaLoadToken) {
        // 古くなった（破棄される）結果の blob URL を解放してリークを防ぐ
        if (result.audioUrl) URL.revokeObjectURL(result.audioUrl);
        const staleImage = result.image_data?.currentImage;
        if (staleImage && typeof staleImage === "string" && staleImage.startsWith("blob:")) URL.revokeObjectURL(staleImage);
        return;
      }
      useAudio.set(result.audio ?? null, result.audioUrl ?? null);
      const { audio: _ignoredAudio, audioUrl: _ignoredUrl, ...rest } = result;
      setLoadedMedia(restoreMediaDraft(data, rest));
      loadedProject = data;
      registerLoadedMedia(data, mediaState.media);
      // メディア切り替え後も音量・倍速を維持
      useAudio.setVol(prevVol);
      useAudio.setRate(prevRate);
    } catch (err) {
      if (token !== mediaLoadToken) return;
      const previousIndex = projectState.jsonDataList.indexOf(loadedProject);
      if (previousIndex >= 0) projectState.mediaIndex = previousIndex;
      showToast("メディア読み込みに失敗しました。", "error");
    } finally {
      if (token === mediaLoadToken) loading = false;
    }
    });
  });

  // UI部品まわりの変数
  let currentColumnIndex = $state(-1);

  const totalWidth = $derived.by(() => {
    return editorLayoutState.columns.reduce((sum, column) => sum + column.width, 0);
  });

  // レイアウト高さは CSS（flex の min-height:0 連鎖）で解決するため、
  // 旧来の getBoundingClientRect ベースの tableHeight 計算は廃止した。

  // メインモデルの監視用
  // $effect(() => {
  //   console.log("json_data_list:", $state.snapshot(json_data_list));
  //   console.log("media_index:", $state.snapshot(media_index));
  //   console.log("media:", $state.snapshot(media));
  //   console.log("style_list:", $state.snapshot(style_list));
  // });

  // フォルダを読み込み、json_dataを作成
  async function handleLoad() {
    if (loading || saving || creating) return;
    flushEditor();
    loading = true;
    let candidate = null;
    try {
      const directory = await window.showDirectoryPicker();
      const permission = await directory.requestPermission({ mode: "readwrite" });
      if (permission !== "granted") {
        showToast("フォルダの書き込み権限がありません。", "error");
        return;
      }
      const result = await getJsonDataList(directory);
      candidate = result.length ? await getMedia(result[0], directory) : getDefaultMedia();
      flushEditor();
      if (hasUnsavedChanges(loadedProject, mediaState.media) &&
          !window.confirm("現在の未保存の変更を破棄して、選択したフォルダに切り替えますか？")) return;
      for (const data of result) {
        const generatedName = getAutoGeneratedVcJsonName(data);
        if (generatedName) {
          const created = [];
          try {
            for (const script of data.scriptFiles ?? []) {
              if (!Array.isArray(script.inlineData)) continue;
              if (!await createSubtitleFile(directory, script.filePath, script.inlineData)) {
                throw new Error("Initial subtitle creation failed");
              }
              created.push(script.filePath);
            }
            if (!await saveJsonFile(directory, generatedName, data)) throw new Error("Project creation failed");
          } catch (error) {
            for (const path of created) await removeCreatedSubtitleFile(directory, path);
            throw error;
          }
        }
      }
      loadedProject = null;
      preparedMedia = candidate;
      candidate = null;
      projectState.dirHandle = directory;
      projectState.folderName = directory.name;
      setProjectDataList(result);
      resetProjectSessions(projectState.jsonDataList);
    } catch (err) {
      if (err?.name !== "AbortError") showToast("フォルダ読み込みに失敗しました。現在のプロジェクトを維持します。", "error");
    } finally {
      if (candidate?.audioUrl) URL.revokeObjectURL(candidate.audioUrl);
      if (candidate?.image_data?.currentImage) URL.revokeObjectURL(candidate.image_data.currentImage);
      loading = false;
    }
  }

  async function save_VC_JSON_File() {
    if (loading || saving || creating || loadedProject !== json_data) return;
    flushEditor();
    if (projectState.dirHandle && json_data?.name && json_data.name !== "dummy") {
      saving = true;
      const project = json_data;
      const snapshot = projectSnapshot(project);
      const nameWithoutExt = mediaState.media.name.replace(/\.[^/.]+$/, "");
      const name = `${nameWithoutExt}.vc_json`;

      const dataToSave = JSON.parse(JSON.stringify(syncJsonDataFromMedia(project, mediaState.media)));
      const success = await saveJsonFile(projectState.dirHandle, name, dataToSave);
      if (success) markProjectSaved(project, snapshot);
      saving = false;
      uiState.jsonSaveStatus = success ? 1 : -1;
      showToast(success ? 'vc_json 保存完了' : 'vc_json 保存失敗', success ? 'success' : 'error');

      // 1秒後にアイコンを通常に戻す
      setTimeout(() => {
        uiState.jsonSaveStatus = 0;
      }, 2000);
    }
  }

  async function save_SRT_Files() {
    if (loading || saving || creating || loadedProject !== json_data) return;
    flushEditor();
    if (projectState.dirHandle) {
      saving = true;
      const project = json_data;
      let saved = 0;
      let failed = 0;
      const paths = new Set();
      for (const track of mediaState.media.srt_data) {
        const key = String(track.file_path ?? "").replace(/\\/g, "/").toLowerCase();
        if (paths.has(key)) continue;
        paths.add(key);
        const snapshot = trackSnapshot(track);
        if (await saveSubtitleTrack(projectState.dirHandle, { ...track, data: JSON.parse(snapshot) })) {
          markTrackSaved(project, track, snapshot);
          saved++;
        } else failed++;
      }
      saving = false;
      const success = saved > 0 && failed === 0;
      uiState.srtSaveStatus = success ? 1 : -1;
      showToast(success ? '字幕 保存完了' : `字幕 保存: ${saved}件成功 / ${failed}件失敗`, success ? 'success' : 'error');

      // 1秒後にアイコンを通常に戻す
      setTimeout(() => {
        uiState.srtSaveStatus = 0;
      }, 2000);
    }
  }

  function sanitizeTrackFileBase(name) {
    return String(name ?? "")
      .trim()
      .replace(/[\\/:*?"<>|]/g, "_")
      .replace(/^\.+/, "")
      .slice(0, 120);
  }

  function existingSubtitlePathSet() {
    return new Set((json_data?.scriptFiles ?? []).map((item) => String(item.filePath ?? item.name ?? "").toLowerCase()));
  }

  async function createSubtitleTrackFromUI() {
    if (loading || saving || creating || loadedProject !== json_data) return;
    flushEditor();
    if (!projectState.dirHandle || !json_data?.scriptFiles) {
      showToast("フォルダを読み込んでから作成してください。", "error");
      return;
    }
    const baseName = sanitizeTrackFileBase(newTrackName);
    if (!baseName) {
      showToast("字幕トラック名を入力してください。", "error");
      return;
    }
    const extension = newTrackFormat === "srt" ? "srt" : "json";
    const filePath = extension === "srt" ? `srt/${baseName}.srt` : `${baseName}.json`;
    if (existingSubtitlePathSet().has(filePath.toLowerCase())) {
      showToast("同じ字幕ファイル名が既にあります。", "error");
      return;
    }

    const id = json_data.scriptFiles.length;
    const defaultStyle = Object.keys(json_data.styles ?? {})[0] ?? "default-style-1";
    const data = [createBlankSubtitleClip(mediaState.media.duration)];
    const scriptFile = createSubtitleScriptFile({ filePath, name: filePath, defaultStyle });
    const track = createSubtitleMediaTrack({ id, name: filePath, filePath, data, defaultStyle });
    creating = true;
    const subtitleSaved = await createSubtitleFile(projectState.dirHandle, filePath, data);
    if (!subtitleSaved) {
      creating = false;
      showToast("字幕トラックを作成できません。既存ファイル名や書き込み権限を確認してください。", "error");
      return;
    }

    addSubtitleTrack(scriptFile, track);
    const addedTrack = mediaState.media.srt_data.find((item) => item.id === track.id);
    markTrackSaved(json_data, addedTrack, trackSnapshot(addedTrack));
    const snapshot = projectSnapshot(json_data);
    const vcJsonName = `${mediaState.media.name.replace(/\.[^/.]+$/, "")}.vc_json`;
    const payload = JSON.parse(JSON.stringify(syncJsonDataFromMedia(json_data, mediaState.media)));
    const vcSaved = await saveJsonFile(projectState.dirHandle, vcJsonName, payload);
    if (vcSaved) markProjectSaved(json_data, snapshot);
    creating = false;
    newTrackName = "";
    showToast(vcSaved ? "字幕トラックを作成しました。" : "字幕は作成しましたが vc_json 保存に失敗しました。", vcSaved ? "success" : "error");
  }

  function scrollEditor() {
    window.dispatchEvent(new CustomEvent("srt-editor-scroll-current", { detail: { time: json_data.seekTime } }));
  }

  function clearOverlaySelectionOutsideRibbon(event) {
    const target = event.target;
    if (target?.closest?.(".ribbonview")) return;
    if (target?.closest?.(".srt_box")) return;
    clearOverlaySelection();
    if (!target?.closest?.('[role="separator"]')) document.activeElement?.blur?.();
  }

  // ドラッグ開始
  const startDrag = (event, index) => {
    event.preventDefault();
    event.currentTarget.focus();
    dragging = true;
    startX = event.clientX;
    currentColumnIndex = index;
    startWidth = editorLayoutState.columns[index]?.width;
    const newColumns = editorLayoutState.columns.map((column) => ({ ...column }));

    const totalWidth = editorLayoutState.columns.reduce((sum, column) => sum + column.width, 0);

    // ドラッグ中の処理（newColumns はドラッグ開始時のスナップショット。
    // ライブ state を読まずスナップショットから計算することで、移動中の累積誤差を防ぐ）
    const onMouseMove = (moveEvent) => {
      if (!dragging) return;
      const diff = moveEvent.clientX - startX;

      if (currentColumnIndex === -1) {
        // プレイヤー↔エディタ全体の境界: 全列を比率で拡縮
        const scale = (totalWidth - diff) / totalWidth;
        editorLayoutState.columns = newColumns.map((column) => ({ ...column, width: Math.max(50, column.width * scale) }));
        return;
      }

      const current = currentColumnIndex;
      const prev = current - 1;
      if (prev < 0) {
        // 先頭列: 隣接列が無いので単独で拡縮
        editorLayoutState.columns = newColumns.map((column, i) =>
          i === current ? { ...column, width: Math.max(50, newColumns[current].width - diff) } : { ...column },
        );
        return;
      }

      // 隣接列との境界: prev+current の合計を保ったまま再配分（合計幅がドラッグ中に増減しない）
      const pair = newColumns[prev].width + newColumns[current].width;
      const newCurrent = Math.max(50, Math.min(newColumns[current].width - diff, pair - 50));
      editorLayoutState.columns = newColumns.map((column, i) => {
        if (i === current) return { ...column, width: newCurrent };
        if (i === prev) return { ...column, width: pair - newCurrent };
        return { ...column };
      });
    };

    // ドラッグ終了時の処理
    const stopDrag = () => {
      dragging = false;
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("mouseup", stopDrag);
    };

    // イベントリスナーを追加
    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", stopDrag);
  };

  function resizeWithKeyboard(event, index) {
    if (!["ArrowLeft", "ArrowRight"].includes(event.key)) return;
    event.preventDefault();
    const delta = (event.key === "ArrowLeft" ? 1 : -1) * (event.shiftKey ? 40 : 10);
    const columns = editorLayoutState.columns;
    if (index === -1) {
      const width = columns.reduce((sum, column) => sum + column.width, 0);
      editorLayoutState.columns = columns.map((column) => ({ ...column, width: Math.max(50, column.width * (width + delta) / width) }));
    } else {
      const amount = Math.max(50 - columns[index].width, Math.min(delta, columns[index - 1].width - 50));
      columns[index].width += amount;
      columns[index - 1].width -= amount;
    }
  }

  async function splitIntoSubtitleBox({ track, data, blockId, before, after }) {
    if (loading || saving || creating || loadedProject !== json_data) return;
    if (!mediaState.media.srt_data.includes(track) || track.loadStatus !== "loaded") return;
    flushEditor();
    const index = track.data.indexOf(data);
    if (index < 0) return;
    const script = json_data.scriptFiles[track.id];
    if (track.file_path.toLowerCase().endsWith(".json")) {
      try {
        let id;
        editClips(track, [data], () => { id = splitSubtitleBlock(data, blockId, before, after, script); });
        selectEditorClip(track.id, index, id);
        selectOverlayTrack(track.id, null, index, id);
        return { index, blockId: id };
      } catch {
        showToast("箱を分割できません。箱の数や字幕の構造を確認してください。", "error");
        return;
      }
    }

    creating = true;
    convertingTrack = true;
    let createdPath = null;
    try {
      const original = JSON.parse(trackSnapshot(track));
      const candidate = JSON.parse(JSON.stringify(original));
      const id = splitSubtitleBlock(candidate[index], blockId, before, after, script);
      const base = track.file_path.replace(/\.srt$/i, "");
      const referencedPaths = new Set(projectState.jsonDataList.flatMap((project) =>
        (project.scriptFiles ?? []).map((item) => String(item.filePath ?? "").replace(/\\/g, "/").toLowerCase())));
      let path;
      for (let suffix = 1; suffix <= 100; suffix++) {
        const proposed = `${base}.boxes${suffix === 1 ? "" : `-${suffix}`}.json`;
        if (referencedPaths.has(proposed.replace(/\\/g, "/").toLowerCase())) continue;
        try {
          await getFileFromPath(projectState.dirHandle, proposed);
        } catch (error) {
          if (error.name !== "NotFoundError") throw error;
          path = proposed;
          break;
        }
      }
      if (!path || !await createSubtitleFile(projectState.dirHandle, path, candidate)) {
        throw new Error("Subtitle JSON creation failed");
      }
      createdPath = path;
      const payload = JSON.parse(JSON.stringify(syncJsonDataFromMedia(json_data, mediaState.media)));
      payload.scriptFiles[track.id].filePath = path;
      payload.scriptFiles[track.id].name = path;
      const vcName = `${mediaState.media.name.replace(/\.[^/.]+$/, "")}.vc_json`;
      if (!await saveJsonFile(projectState.dirHandle, vcName, payload)) throw new Error("Project reference save failed");

      // Detach this JSON source from other projects that still reference the original SRT.
      const sourceData = track.data;
      track.data = original;
      forkEditorHistory(sourceData, track.data, (value) => {
        let reactiveClip = $state(value);
        return reactiveClip;
      });
      track.file_path = path;
      track.name = path;
      script.filePath = path;
      script.name = path;
      editClips(track, [track.data[index]], () => {
        const target = track.data[index];
        for (const key of ["text", "sentences", "layout", "additionalBlocks"]) {
          if (candidate[index][key] === undefined) delete target[key];
          else target[key] = candidate[index][key];
        }
      });
      markTrackSaved(json_data, track, trackSnapshot(track));
      markProjectSaved(json_data, projectSnapshot(json_data));
      createdPath = null;
      selectEditorClip(track.id, index, id);
      selectOverlayTrack(track.id, null, index, id);
      showToast(`元SRTを残し、${path} に保存しました。`);
      return { index, blockId: id };
    } catch {
      if (createdPath) await removeCreatedSubtitleFile(projectState.dirHandle, createdPath);
      showToast("箱を分割できませんでした。元の字幕と参照先を維持します。", "error");
    } finally {
      creating = false;
      convertingTrack = false;
    }
  }

  onMount(() => {
    const preventDiscard = (event) => {
      flushEditor();
      if (!hasUnsavedChanges(loadedProject, mediaState.media) && !loading && !saving && !creating) return;
      event.preventDefault();
      event.returnValue = "";
    };
    window.addEventListener("beforeunload", preventDiscard);
    return () => {
      window.removeEventListener("beforeunload", preventDiscard);
      clearTimeout(toastTimer);
    };
  });
</script>

<svelte:window onmousedown={clearOverlaySelectionOutsideRibbon} />
<main inert={loading || convertingTrack}>
  <header class="app-toolbar surface-controls">
    <div class="folder-path">{projectState.folderName}</div>

    <div class="toolbar-group">
      <button class="nmorph_button" title="フォルダを開く" aria-label="フォルダを開く" disabled={loading || saving || creating} onclick={handleLoad}>
        <span class="material-symbols-outlined"> folder_open </span>
      </button>
      <button
        class="nmorph_button"
        title="前のメディア"
        aria-label="前のメディア"
        disabled={loading || saving || creating || projectState.mediaIndex <= 0}
        onclick={() => {
          if (projectState.mediaIndex > 0) {
            flushEditor();
            projectState.mediaIndex -= 1;
          }
        }}
      >
        <span class="material-symbols-outlined"> chevron_left </span>
      </button>
      <select class="folder-path media-select" aria-label="メディア選択" disabled={loading || saving || creating} bind:value={projectState.mediaIndex}>
        {#each projectState.jsonDataList as jsondata, index}
          <option value={index}>{jsondata.name}</option>
        {/each}
      </select>
      <button
        class="nmorph_button"
        title="次のメディア"
        aria-label="次のメディア"
        disabled={loading || saving || creating || projectState.mediaIndex >= projectState.jsonDataList.length - 1}
        onclick={() => {
          if (projectState.mediaIndex < projectState.jsonDataList.length - 1) {
            flushEditor();
            projectState.mediaIndex += 1;
          }
        }}
      >
        <span class="material-symbols-outlined"> chevron_right </span>
      </button>
      <button class="nmorph_button" title="vc_jsonを保存" aria-label="vc_jsonを保存" disabled={loading || saving || creating || !projectState.dirHandle} onclick={save_VC_JSON_File}>
        {#if uiState.jsonSaveStatus == 0}
          <span class="material-symbols-outlined"> save_as </span>
        {:else if uiState.jsonSaveStatus > 0}
          <span class="material-symbols-outlined"> check </span>
        {:else}
          <span class="material-symbols-outlined"> error </span>
        {/if}
      </button>
    </div>

    <div class="toolbar-group toggles">
      <label class="toggle-field" title="字幕枠の編集ハンドル表示">
        <span class="head-text">Edit Frame</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.viewSrtFrame} />
          <span class="toggle-slider"></span>
        </span>
      </label>
      <label class="toggle-field" title="再生に追従して字幕エディタをスクロール">
        <span class="head-text">Auto Scroll</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.autoScroll} id="AutoScrollButton" />
          <span class="toggle-slider"></span>
        </span>
      </label>
      <label class="toggle-field" title="スタイルリボンの表示">
        <span class="head-text">Ribbon</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.viewRibbon} />
          <span class="toggle-slider"></span>
        </span>
      </label>
      <label class="toggle-field" title="タイムラインの表示">
        <span class="head-text">Timeline</span>
        <span class="toggle_switch">
          <input type="checkbox" bind:checked={uiState.viewTrack} />
          <span class="toggle-slider"></span>
        </span>
      </label>
    </div>
  </header>

  {#if uiState.viewRibbon}
    <StyleRibbon></StyleRibbon>
  {/if}

  {#if toastMessage}
    <div class="toast toast-{toastType}">{toastMessage}</div>
  {/if}
  {#if projectState.jsonDataList.length > projectState.mediaIndex && json_data?.styles}
    <section class="workspace-table" bind:this={useRefs.tableRef}>
      <!-- 左: メディアプレイヤー -->
      <div class="player-pane">
        {#if mediaState.media}
          <MediaPlayer />
        {/if}
        {#if showQuickStart}
          <!-- フォルダ未選択時のみ、プレイヤー上に重ねて表示する（レイアウトフローには入れない） -->
          <section class="quick-start" aria-label="使い方">
            <div class="quick-start-title">
              <span class="material-symbols-outlined">info</span>
              <span>使い方</span>
            </div>
            <ol>
              <li><span>1</span>フォルダを開く</li>
              <li><span>2</span>メディアを選ぶ</li>
              <li><span>3</span>字幕を編集して保存</li>
            </ol>
          </section>
        {/if}
      </div>

      <!-- リサイズバー（プレイヤー↔編集エリア） -->
      <!-- svelte-ignore a11y_no_noninteractive_tabindex a11y_no_noninteractive_element_interactions (Focusable ARIA window splitter supports arrow-key resizing.) -->
      <div class="resizer" class:dragging={dragging && currentColumnIndex === -1} role="separator" aria-orientation="vertical" aria-valuemin="50" aria-valuemax="10000" aria-valuenow={Math.round(totalWidth)} tabindex="0" aria-label="プレイヤーと編集エリアの境界" onkeydown={(event) => resizeWithKeyboard(event, -1)} onmousedown={(event) => startDrag(event, -1)}></div>

      <!-- 右: 編集エリア（列の合計幅 totalWidth に左右パディング分を足した値を上限にし、
           プレイヤーとの取り合いで幅が足りない時は縮小＋内部横スクロールで収める） -->
      <div class="srt_area" style="max-width: calc({totalWidth}px + 18px);">
        <!-- 折り返しはグループ単位（ボタン1個だけが次の行に落ちる崩れを防ぐ） -->
        <div class="editor-toolbar">
          <div class="toolbar-cluster">
            <button class="nmorph_button" title="列を減らす" aria-label="列を減らす" onclick={removeEditorColumn}>
              <span class="material-symbols-outlined"> chevron_left </span>
            </button>
            <span class="col-count">{editorLayoutState.columns.length}</span>
            <button class="nmorph_button" title="列を増やす" aria-label="列を増やす" onclick={addEditorColumn}>
              <span class="material-symbols-outlined"> chevron_right </span>
            </button>
            <button class="nmorph_button" onclick={scrollEditor} title="再生位置にスクロール"> Scroll </button>
          </div>
          <div class="toolbar-cluster track-create">
            <input class="new-track-name" data-testid="new-subtitle-track-name" type="text" bind:value={newTrackName} placeholder="new subtitle" />
            <select class="new-track-format" data-testid="new-subtitle-track-format" bind:value={newTrackFormat}>
              <option value="json">json</option>
              <option value="srt">srt</option>
            </select>
            <button class="nmorph_button" data-testid="create-subtitle-track" disabled={loading || saving || creating || !projectState.dirHandle} onclick={createSubtitleTrackFromUI} title="字幕トラックを作成" aria-label="字幕トラックを作成">
              <span class="material-symbols-outlined"> playlist_add </span>
            </button>
            <button class="nmorph_button" disabled={loading || saving || creating || !projectState.dirHandle} onclick={save_SRT_Files} title="字幕を保存" aria-label="字幕を保存">
              {#if uiState.srtSaveStatus == 0}
                <span class="material-symbols-outlined"> save_as </span>
              {:else if uiState.srtSaveStatus > 0}
                <span class="material-symbols-outlined"> check </span>
              {:else}
                <span class="material-symbols-outlined"> error </span>
              {/if}
            </button>
          </div>
        </div>

        <div class="editor-columns">
          {#each editorLayoutState.columns as column, index (column.id)}
            <div class="editor-column" style="width: {column.width}px;">
              {#if index > 0}
                <!-- svelte-ignore a11y_no_noninteractive_tabindex a11y_no_noninteractive_element_interactions (Focusable ARIA window splitter supports arrow-key resizing.) -->
                <div class="resize-bar" class:dragging={dragging && currentColumnIndex === index} role="separator" aria-orientation="vertical" aria-valuemin="50" aria-valuemax="10000" aria-valuenow={Math.round(column.width)} tabindex="0" aria-label="列幅の調整" onkeydown={(event) => resizeWithKeyboard(event, index)} onmousedown={(event) => startDrag(event, index)}></div>
              {/if}
              <div class="editor-column-body">
                <SrtEditor bind:this={useRefs.editorRefs[index]} column={column} onsplitbox={splitIntoSubtitleBox} />
              </div>
            </div>
          {/each}
        </div>
      </div>
    </section>

    <div class="track-shell" bind:this={useRefs.trackRef}>
      <WorkspaceControls onscrolltimeline={() => trackView?.scrollTimeLine()} />
      {#if uiState.viewTrack}
        <TrackView bind:this={trackView} />
      {/if}
    </div>
  {/if}
</main>

<style>
  main {
    padding: 8px 12px 6px;
    height: 100dvh;
    box-sizing: border-box;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .track-shell {
    display: flex;
    flex-direction: column;
    min-height: 0;
    flex-shrink: 0;
    gap: 4px;
  }

  /* ── 上部ツールバー（折り返し対応・グループ化） ── */
  .app-toolbar {
    flex: 0 0 auto;
    display: grid;
    grid-template-columns: minmax(160px, 320px) minmax(300px, 452px) 1fr;
    align-items: center;
    gap: 6px 12px;
    padding: 2px 0 4px;
  }
  .toolbar-group {
    display: grid;
    grid-template-columns: 32px 32px minmax(120px, 1fr) 32px 32px;
    align-items: center;
    gap: var(--space-control);
    min-width: 0;
  }
  .toolbar-group.toggles {
    grid-template-columns: repeat(4, max-content);
    gap: 6px 14px;
    justify-self: end;
  }
  .toggle-field {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    cursor: pointer;
    white-space: nowrap;
    color: #c5d0d2;
    min-height: var(--control-height);
  }
  .toggle-field .head-text {
    margin: 0;
    color: #27b1b5;
    font-size: 14px;
  }
  .toggle_switch input {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    margin: 0;
    opacity: 0;
    cursor: pointer;
  }
  .media-select {
    min-width: 0;
    width: 100%;
    color: #dbe4e5;
    cursor: pointer;
  }

  /* ── ワークスペース（プレイヤー | 編集エリア） ── */
  .workspace-table {
    flex: 1 1 auto;
    min-height: 120px; /* 旧 tableHeight の Math.max(120, ...) と同じ下限を維持する */
    display: flex;
    align-items: stretch;
    width: 100%;
  }
  .player-pane {
    flex: 1 1 0;
    min-width: 220px; /* プレイヤーが0幅まで潰れて操作不能にならないための下限 */
    min-height: 0;
    display: flex;
    position: relative; /* quick-start オーバーレイの基準 */
  }
  .player-pane > :global(.media-player) {
    flex: 1 1 auto;
    min-width: 0;
    min-height: 0;
  }

  /* ── 編集エリア内 ── */
  .editor-toolbar {
    flex: 0 0 auto;
    display: grid;
    grid-template-columns: max-content minmax(0, 1fr);
    align-items: center;
    gap: var(--space-control) var(--space-group);
    min-height: 32px;
    padding: 0 0 8px;
    border-bottom: 1px solid #313638;
  }
  .toolbar-cluster {
    display: grid;
    grid-template-columns: 32px 18px 32px max-content;
    align-items: center;
    gap: var(--space-control);
    min-width: 0;
  }
  .toolbar-cluster.track-create {
    grid-template-columns: minmax(44px, 130px) 56px 32px 32px;
    justify-content: end;
  }
  .editor-toolbar :global(.nmorph_button) {
    margin: 0; /* 間隔は gap で取る。グローバルの margin: 5px 10px は幅を圧迫して折り返しの原因になる */
  }
  .toolbar-cluster.track-create .new-track-name {
    width: 100%;
    min-width: 0;
    max-width: 130px;
  }
  .col-count {
    min-width: 18px;
    text-align: center;
    color: #b4b4b4;
    font-variant-numeric: tabular-nums;
  }
  .editor-columns {
    flex: 1 1 auto;
    min-height: 0;
    min-width: 0; /* overflow-x を効かせるため、内容幅で親を押し広げないようにする */
    display: flex;
    align-items: stretch;
    overflow-x: auto; /* 列合計幅が収まりきらない時は内部横スクロールで到達可能にする */
    overflow-y: hidden; /* 縦は各列内の .box がスクロールを担う。ここに縦バーを出すと二重スクロールになる */
  }
  .editor-column {
    position: relative;
    display: flex;
    min-height: 0;
    flex: 0 0 auto;
  }
  .editor-column-body {
    flex: 1 1 auto;
    min-width: 0;
    min-height: 0;
    display: flex;
  }
  .editor-column-body > :global(.srt-editor) {
    flex: 1 1 auto;
    min-width: 0;
  }

  .folder-path {
    margin: 0;
    display: inline-block;
    padding: 2px 10px;
    min-width: 0;
    width: 100%;
    height: var(--control-height);
    box-sizing: border-box;
    vertical-align: middle;
    align-content: center;
    font-size: 15px;
    border-radius: 5px;
    color: #dbe4e5;
    background: #1d2022;
    border: 1px solid #3d4547;
    box-shadow: inset 0 1px 0 #ffffff12;

    overflow-x: auto;
    white-space: nowrap;
    cursor: default;

    /* スクロールバー非表示 */
    scrollbar-width: none; /* Firefox */
    -ms-overflow-style: none; /* IE/Edge */

    user-select: text;
  }
  .folder-path::-webkit-scrollbar {
    display: none; /* Chrome/Safari */
  }

  .resizer {
    flex: 0 0 11px;
    align-self: stretch;
    position: relative;
    cursor: ew-resize;
    background-color: transparent;
    margin: 0;
    padding: 0;
  }

  .resize-bar {
    flex: 0 0 14px;
    align-self: stretch;
    position: relative;
    cursor: col-resize;
    background-color: transparent;
    margin: 0;
    padding: 0;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  /* 中心線を描画 */
  .resizer::before,
  .resize-bar::before {
    content: "";
    position: absolute;
    width: 3px;
    height: 30px;
    border-radius: 4px;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    background-color: #505050fd;
    pointer-events: none; /* クリックを通す */
    box-shadow: -1px -1px 1px #b8b8b82c;
  }

  .new-track-name {
    height: var(--control-height);
    box-sizing: border-box;
    color: var(--text-color);
    background-color: var(--input-bg);
    border: 1px solid var(--border-color);
    border-radius: 4px;
  }
  .new-track-format {
    height: var(--control-height);
    color: var(--text-color);
    background-color: var(--input-bg);
    border: 1px solid var(--border-color);
    border-radius: 4px;
  }
  .resizer:hover::before,
  .resize-bar:hover::before,
  .dragging::before {
    background: var(--primary-color);
  }
  .resizer:focus-visible,
  .resize-bar:focus-visible {
    outline: 2px solid var(--focus-color);
    outline-offset: -2px;
  }

  .material-symbols-outlined {
    font-size: 18px;
    vertical-align: middle;
    font-variation-settings:
      "FILL" 1,
      "wght" 400,
      "GRAD" 0,
      "opsz" 48;
  }
  .srt_area {
    flex: 0 1 auto; /* 列合計幅までは伸びるが、プレイヤー側が足りない時は縮小を許可する */
    /* Inline-size containment needs an explicit width; the column total caps it inline. */
    width: 100%;
    min-width: 200px; /* 縮小してもツールバーのボタン類が残る最低限の幅 */
    min-height: 0;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    padding: 8px 8px 7px;
    background-color: var(--panel-bg);
    border: 1px solid transparent;
    box-shadow: var(--panel-shadow);
    border-radius: 8px;
    container-type: inline-size;
    container-name: editor-panel;
  }

  @container editor-panel (max-width: 440px) {
    .editor-toolbar {
      grid-template-columns: 1fr;
    }
    .toolbar-cluster.track-create {
      justify-content: start;
    }
  }

  @media (max-width: 1280px) {
    .app-toolbar {
      grid-template-columns: minmax(160px, 320px) minmax(300px, 1fr);
    }
    .toolbar-group.toggles {
      grid-column: 1 / -1;
    }
  }

  @media (max-width: 720px) {
    .app-toolbar {
      grid-template-columns: minmax(0, 1fr);
    }
    .toolbar-group.toggles {
      grid-template-columns: repeat(2, max-content);
      justify-self: start;
    }
  }

  .quick-start {
    /* レイアウトフローに入れず、プレイヤー領域の上部中央にフローティング表示する */
    position: absolute;
    top: 16px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 5;
    pointer-events: none; /* 下のプレイヤー操作を邪魔しない */
    max-width: calc(100% - 24px);
    box-sizing: border-box;
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 8px 12px;
    padding: 8px 12px;
    border: 1px solid #334245;
    border-radius: 8px;
    background: #202426f0;
    box-shadow: 0 8px 18px #00000055;
    color: #cbd5d7;
  }
  .quick-start-title {
    display: inline-flex;
    align-items: center;
    gap: 7px;
    color: #2cc5c5;
    font-weight: 600;
    white-space: nowrap;
  }
  .quick-start-title .material-symbols-outlined {
    font-size: 18px;
  }
  .quick-start ol {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 10px 16px;
    margin: 0;
    padding: 0;
    list-style: none;
    font-size: 13px;
  }
  .quick-start li {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    min-width: 0;
    white-space: normal;
  }
  .quick-start li span {
    flex: 0 0 18px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: #2e3d40;
    color: #bfeeee;
    font-size: 12px;
  }

  /* トースト通知 */
  .toast {
    position: fixed;
    bottom: 24px;
    right: 24px;
    padding: 10px 18px;
    border-radius: 6px;
    font-size: 14px;
    z-index: 9999;
    pointer-events: none;
    animation: toast-in 0.2s ease;
  }
  .toast-success { background: #1a5c3a; color: #b8f5d0; }
  .toast-error   { background: #6b1a1a; color: #ffd6d6; }
  @keyframes toast-in {
    from { opacity: 0; transform: translateY(8px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  /* 非活性ボタン */
  button:disabled {
    opacity: 0.3;
    cursor: not-allowed;
  }
</style>
